DevWs
SmartThingsCommunity/SmartThingsPublic pull request #11209
Opened 2019-08-22 07:51 UTC by computime-jasonchan

2019-08-28 04:50 UTC, shrakuma commented
@computime-jasonchan please take a look at the above comments as they would need to be fixed and possibly may need a new PR.
cc @tpmanley @greens @MAblewiczS

2019-08-28 04:50 UTC, shrakuma requested changes

2019-08-28 04:50 UTC, shrakuma commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0702, 0B05", outClusters: "0003, 000A, 0019", manufacturer: "Jasco Products", model: "45853", deviceJoinName: "GE ZigBee Pl
@computime-jasonchan  Can you please let us know the reason for the removal of the code here. This fingerprint is for GE and we cannot remove that.

2019-08-28 04:50 UTC, shrakuma commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0702", outClusters: "0000", manufacturer: "ClimaxTechnology", model: "PSM_00.00.00.35TC", deviceJoinName: "Ozom Smart Plug"
@computime-jasonchan  same here -  a piece of code is removed which should not be done as it affects that partner

2019-08-28 04:50 UTC, shrakuma commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0702, 0003, 0009, 0B04, 0006, 0004, 0005, 0002", outClusters: "0000, 0019, 000A, 0003, 0406", manufacturer: "Aurora", model: "Smart16ARelay51AU", d
@computime-jasonchan  these 2 lines were removed and these are again production fingerprints for another device. please revert these changes and re-submit a new PR

2019-08-28 04:50 UTC, shrakuma commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -	if ((device.getDataValue("manufacturer") == "Develco Products A/S") || (device.getDataValue("manufacturer") == "Aurora"))  {
why was the (device.getDataValue("manufacturer") == "Aurora")) removed?

2019-08-28 05:48 UTC, computime-jasonchan commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0702, 0B05", outClusters: "0003, 000A, 0019", manufacturer: "Jasco Products", model: "45853", deviceJoinName: "GE ZigBee Pl
The reason is those GE and Aurora code is added after I commit my change.

I have check the master branch already include my change and those GE and Aurora change, Do I still needed to commit another PR?

2019-08-28 05:51 UTC, computime-jasonchan commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0702, 0003, 0009, 0B04, 0006, 0004, 0005, 0002", outClusters: "0000, 0019, 000A, 0003, 0406", manufacturer: "Aurora", model: "Smart16ARelay51AU", d
The reason is those line is added after my submission.

Master branch already include my change and the change you mentioned, still need another PR?

2019-08-28 05:51 UTC, computime-jasonchan commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -	if ((device.getDataValue("manufacturer") == "Develco Products A/S") || (device.getDataValue("manufacturer") == "Aurora"))  {
The reason is those line is added after my submission.

Master branch already include my change and the change you mentioned, still need another PR?

2019-08-28 17:20 UTC, greens commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0702, 0003, 0009, 0B04, 0006, 0004, 0005, 0002", outClusters: "0000, 0019, 000A, 0003, 0406", manufacturer: "Aurora", model: "Smart16ARelay51AU", d
your PR just needs to be rebased onto the updated `master` branch

2019-08-30 04:09 UTC, computime-jasonchan commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0702, 0003, 0009, 0B04, 0006, 0004, 0005, 0002", outClusters: "0000, 0019, 000A, 0003, 0406", manufacturer: "Aurora", model: "Smart16ARelay51AU", d
I rebased and update again. Please check if that is OK?

2019-08-30 17:43 UTC, greens commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0702, 0003, 0009, 0B04, 0006, 0004, 0005, 0002", outClusters: "0000, 0019, 000A, 0003, 0406", manufacturer: "Aurora", model: "Smart16ARelay51AU", d
No. If you've set the upstream repo of your for correctly, you should be able to do:

`git fetch upstream master`
`git rebase upstream/master`
`git push origin`

I'm guessing that the `master` branch you're rebasing onto is out of date.

2019-09-10 05:17 UTC, shrakuma commented on devicetypes/smartthings/zigbee-switch-power.src/zigbee-switch-power.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0702, 0003, 0009, 0B04, 0006, 0004, 0005, 0002", outClusters: "0000, 0019, 000A, 0003, 0406", manufacturer: "Aurora", model: "Smart16ARelay51AU", d
@computime-jasonchan can you please take a look at the above comment

2019-09-10 05:19 UTC, shrakuma commented
@computime-jasonchan  not sure if my comments came throuhg correctly 
per @greens  please take a look at 
If you've set the upstream repo of your branch correctly, you should be able to do:

git fetch upstream master
git rebase upstream/master
git push origin

I'm guessing that the master branch you're rebasing onto is out of date.

2019-09-10 13:07 UTC, tpmanley commented
@computime-jasonchan what fingerprint were you trying to add in this PR? It doesn't look like any new fingerprints are added in this PR (perhaps added in a different one?) so I'm wondering if we can just close this.

2019-09-11 07:23 UTC, computime-jasonchan commented
My model is SX885ZB, I have checked that is in Master already.

2019-09-11 16:22 UTC, tpmanley commented
Since the fingerprint was already added I'm going to close this PR.

2019-09-11 16:22 UTC, closed without merging