DevWs
SmartThingsCommunity/SmartThingsPublic pull request #11242
Opened 2019-09-01 04:03 UTC by sxl1987

2019-09-10 06:40 UTC, shrakuma commented
@MAblewiczS can you please triage this to your team for review 

cc @greens @tpmanley

2019-09-10 08:27 UTC, MAblewiczS commented
@sxl1987  Please bring you fork up to date to SmartThingsCommunity:master. You are removing FP for other partners.

2019-09-10 08:52 UTC, MAblewiczS commented
@sxl1987 Also please resolve merge conficts (maybe some of them are related to outdated fork).

2019-09-10 13:48 UTC, tpmanley commented
FYI I just checked in a change that organized all the fingerprints by manufacturer but this is causing some conflicts in your PR. It might be easiest to just reset your branch to the latest `upstream/master`, re-add your changes to the appropriate section and then force push. Something like this:

```
git fetch
git reset --hard upstream/master
<manually re-add your fingerprints to the correct section>
git push -f origin devws_1
```

2019-09-16 08:36 UTC, shrakuma commented
@tpmanley @MAblewiczS @greens  can you please check if the latest updates made are ok?

2019-09-16 12:53 UTC, MAblewicz requested changes
@sxl1987 Please check my comments and resolve them.
@tpmanley  Is it ok to do this kind of cleaning in DTH by partner. It was very hard to quickly review this.

2019-09-16 12:53 UTC, MAblewicz commented on devicetypes/smartthings/zigbee-dimmer.src/zigbee-dimmer.groovy
> +        fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0008, 0B05, 1000, FEDC", outClusters: "000A, 0019", manufacturer: "LDS", model: "ZBT-DIMLight-GLS0006", deviceJoinNam
Please use tabs as indentation and keep correct file formating.

2019-09-16 12:53 UTC, MAblewicz commented on devicetypes/smartthings/zigbee-dimmer.src/zigbee-dimmer.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0008, 0B05, 1000, FC82", outClusters: "0019", manufacturer: "innr", model: "BF 263", deviceJoinName: "INNR Smart Filament B
@sxl1987 Please bring you fork up to date to SmartThingsCommunity:master. You are removing FP for other partners.

2019-09-16 12:53 UTC, MAblewicz commented on devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy
> -		fingerprint profileId: "0104", inClusters: "0000,0003,0004,0005,0006,0008,0300,0702,0B05,FC03,FC04", outClusters: "0019", manufacturer: "sengled", model: "E11-N1EA", deviceJoinName: "Sengled Elemen
@sxl1987 Are you sure about removing/changing those Fingerprint. It looks like those are diffrent models?

2019-09-16 12:53 UTC, MAblewiczS commented on devicetypes/smartthings/zigbee-dimmer.src/zigbee-dimmer.groovy
> -		fingerprint mfr:"innr", model:"RF 265", deviceJoinName: "Innr Smart Filament Bulb White" // raw description: 01 0104 0101 01 09 0000 0003 0004 0005 0006 0008 0B05 1000 FC82 01 0019
@sxl1987 Why is this finterprint removed (fingerprint mfr:"innr", model:"RF 265", deviceJoinName: "Innr Smart Filament Bulb White") . You did some cleaning and for rest removed FP you re-add them but not this one.

2019-09-16 12:53 UTC, MAblewiczS commented on devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy
> -		fingerprint profileId: "0104", inClusters: "0000,0003,0004,0005,0006,0008,0300,0702,0B05,FC03,FC04", outClusters: "0019", manufacturer: "sengled", model: "E12-N1E", deviceJoinName: "Sengled Element
@sxl1987 Are you sure about removing/changing those Fingerprint. It looks like those are diffrent models?

2019-09-23 15:00 UTC, tpmanley approved these changes

2019-09-23 15:18 UTC, MAblewicz approved these changes
Look ok now.

2019-09-23 15:18 UTC, merged