[CHF-156] Health Check NYCE Door/Window Sensor NCZ-3011
SmartThingsCommunity/SmartThingsPublic pull request #1139
Opened 2016-08-23 11:29 UTC by parijatdas

Added health checks for NYCE door/window sensor
checkInterval value determined and added
Implemented ping functionality

2016-08-23 16:07 UTC, jackchi commented
👍 looks good.

2016-09-29 11:47 UTC, parijatdas commented
@jackchi We've removed the temporary fix for ping and changed the checkInterval to 12min with the reporting interval being configured at 5min. Please check and merge the changes.

2016-09-30 21:31 UTC, jackchi requested changes

2016-09-30 21:31 UTC, jackchi commented on devicetypes/smartthings/nyce-open-closed-sensor.src/nyce-open-closed-sensor.groovy
>  		capability "Configuration"
Odd formatting here.

2016-09-30 21:31 UTC, jackchi commented on devicetypes/smartthings/nyce-open-closed-sensor.src/README.md
> +* [Health]($health)
Broken link.

2016-10-03 11:40 UTC, parijatdas commented on devicetypes/smartthings/nyce-open-closed-sensor.src/nyce-open-closed-sensor.groovy
>  		capability "Configuration"
Fixed the indentation in the metadata section. Please check.

2016-10-03 11:41 UTC, parijatdas commented on devicetypes/smartthings/nyce-open-closed-sensor.src/README.md
> +* [Health]($health)
This is fixed now. Please check.

2016-10-04 23:10 UTC, jackchi commented on devicetypes/smartthings/nyce-open-closed-sensor.src/nyce-open-closed-sensor.groovy
> +	definition (name: "NYCE Open/Closed Sensor", namespace: "smartthings", author: "NYCE", category: "C2") {
Let's remove `Category`.

2016-10-04 23:10 UTC, jackchi approved these changes

2016-10-04 23:10 UTC, jackchi commented
👍  Looks good once we remove the Category.

2016-10-05 16:34 UTC, merged