DevWs for Ajaxonline Ltd containing containing Ajax RGBCCT
SmartThingsCommunity/SmartThingsPublic pull request #11447
Opened 2019-10-21 16:58 UTC by SmartThings

Ajax RGBCCT

2019-10-22 11:39 UTC, MAblewiczS commented
@Ajax-online please look at my comments now. You are changing correct file this time but please do not remove Fingeprints of other partners. Just add yours at the end of fingerprint list (like you did) after sengled section.

2019-10-22 11:39 UTC, MAblewicz requested changes

2019-10-22 11:39 UTC, MAblewiczS commented on devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy
> +        fingerprint profileId: "0104", deviceId: "010D", inClusters: "0006, 0008, 0300", deviceJoinName: "Ajax RGBCCT"
Use tabs instead of spaces

2019-10-22 11:39 UTC, MAblewiczS commented on devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy
> -
Please leave other partners fingeprint intact. Do not remove them.

2020-07-02 09:00 UTC, PKacprowiczS requested changes

2020-07-02 09:00 UTC, PKacprowiczS commented on devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy
> +	definition (name: "Ajax RGBCW STRIP", namespace: "smartthings", author: "SmartThings", runLocally: true, minHubCoreVersion: '000.019.00012', executeCommandsLocally: true, genericHandler: "Zigbee") {
Name shouldn't be changed

2020-07-02 09:00 UTC, PKacprowiczS commented on devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy
> +        fingerprint profileId: "0104", deviceId: "010D", inClusters: "0006, 0008, 0300", deviceJoinName: "Ajax RGBCCT"
Once again - please, use tabs instead of spaces

2020-07-06 18:08 UTC, Ajax-online commented
Hi thank you for this

But still I don’t understand

Could you please help – If possible can send me the file and I will copy ?




Regards,
Ajay Assani

[cid:image006.png@01D653C8.D5F62010]

sales@ajaxonline.co.uk<mailto:sales@ajaxonline.co.uk>
www.ajaxonline.co.uk
WeChat : Ajaxonline

Follow us on social media:

[cid:image007.png@01D653C8.D5F62010]<https://www.facebook.com/ajaxonline.co.uk/> [cid:image008.png@01D653C8.D5F62010] <https://www.youtube.com/channel/UC5JTEreIY01KdkEGzfXynjw>  [cid:image009.png@01D653C8.D5F62010] <https://www.instagram.com/ajaxonline.co.uk/>  [cid:image010.png@01D653C8.D5F62010] <https://twitter.com/Ajaxonlineltd>

This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Ajax Online Ltd. If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this email in error.

From: Mariusz A <notifications@github.com>
Sent: 22 October 2019 12:40
To: SmartThingsCommunity/SmartThingsPublic <SmartThingsPublic@noreply.github.com>
Cc: Ajay Assani <sales@ajaxonline.co.uk>; Mention <mention@noreply.github.com>
Subject: Re: [SmartThingsCommunity/SmartThingsPublic] DevWs for Ajaxonline Ltd containing containing Ajax RGBCCT (#11447)


@MAblewiczS requested changes on this pull request.

________________________________

In devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy<https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/11447#discussion_r337463614>:

> -            fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0008, 0300, 0B05, FC01", outClusters: "0019", manufacturer: "LEDVANCE", model: "Flex RGBW Pro", deviceJoinName: "SYLVANIA Smart Flex 11 RGBW"

-

-              // Leedarson/Ozom

-              fingerprint profileId: "0104", inClusters: "0000, 0004, 0003, 0006, 0008, 0005, 0300", outClusters: "0019", manufacturer: "LEEDARSON LIGHTING", model: "5ZB-A806ST-Q1G", deviceJoinName: "Ozom Multicolor Smart Light"

-

-              // Sengled

-              fingerprint profileId: "0104", inClusters: "0000,0003,0004,0005,0006,0008,0300,0702,0B05,FC03,FC04", outClusters: "0019", manufacturer: "sengled", model: "E11-N1EA", deviceJoinName: "Sengled Multicolor"

-                fingerprint profileId: "0104", inClusters: "0000,0003,0004,0005,0006,0008,0300,0702,0B05,FC03,FC04", outClusters: "0019", manufacturer: "sengled", model: "E12-N1E", deviceJoinName: "Sengled Element Color Plus"

-              fingerprint profileId: "0104", inClusters: "0000,0003,0004,0005,0006,0008,0300,0702,0B05,FC03,FC04", outClusters: "0019", manufacturer: "sengled", model: "E21-N1EA", deviceJoinName: "Sengled Multicolor"

-              fingerprint manufacturer: "sengled", model: "E1G-G8E", deviceJoinName: "Sengled Smart Light Strip", mnmn:"SmartThings", vid: "generic-rgbw-color-bulb-2000K-6500K"

-              fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0008, 0300, 0702, 0B05, FC03", outClusters: "0019", manufacturer: "sengled", model: "E11-U3E", deviceJoinName: "Sengled Element Color Plus", mnmn:"SmartThings", vid: "generic-rgbw-color-bulb-2000K-6500K"

-              fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0008, 0300, 0702, 0B05, FC03", outClusters: "0019", manufacturer: "sengled", model: "E11-U2E", deviceJoinName: "Sengled Element Color Plus"

+

+              //Ajax Online

+              fingerprint profileId: "0104", deviceId: "0102", inClusters: "0006, 0008, 0300", deviceJoinName: "Ajax RGBCCT"

+        fingerprint profileId: "0104", deviceId: "010D", inClusters: "0006, 0008, 0300", deviceJoinName: "Ajax RGBCCT"

Use tabs instead of spaces

________________________________

In devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy<https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/11447#discussion_r337463862>:

> @@ -35,51 +35,12 @@ metadata {

                // Generic fingerprint

               fingerprint profileId: "0104", deviceId: "0102", inClusters: "0006, 0008, 0300", deviceJoinName: "Generic RGBW Light"

               fingerprint profileId: "0104", deviceId: "010D", inClusters: "0006, 0008, 0300", deviceJoinName: "Generic RGBW Light"

-

Please leave other partners fingeprint intact. Do not remove them.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/11447?email_source=notifications&email_token=ANM72KFE6RM64S6T3KPTNVDQP3RBPA5CNFSM4JDBCD3KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCIYADQA#pullrequestreview-305136064>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANM72KCQUNM236THVG4X6ZTQP3RBPANCNFSM4JDBCD3A>.

2020-07-08 14:34 UTC, tpmanley commented
There is a newer PR for what looks like the same device so I'm going to close this PR

https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/32385

2020-07-08 14:34 UTC, closed without merging