MSA-1511: Device handlers for OSRAM LIGHTIFY PAR16 RGBW and OUTDOOR RGBW Flex
SmartThingsCommunity/SmartThingsPublic pull request #1313
Opened 2016-10-04 05:03 UTC by yafenzhang

Submitting 'Device handlers for OSRAM LIGHTIFY PAR16 RGBW and OUTDOOR RGBW Flex' for publication

2016-10-04 23:04 UTC, jackchi requested changes

2016-10-04 23:04 UTC, jackchi commented on devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy
> -        capability "Health Check"
We need to `Health Check` this device.

2016-10-04 23:04 UTC, jackchi commented on devicetypes/smartthings/zigbee-rgbw-bulb.src/zigbee-rgbw-bulb.groovy
> + *  Author: Zhangyafen390@126.com
Let's keep authors out of DTH

2016-10-26 07:53 UTC, yafenzhang commented
Close it due to the conflicts. Resubmit it in the pull request #1397

2016-10-26 07:53 UTC, closed without merging