[CHF-441] Added Health Check Implementation for WeMo LED Bulb
SmartThingsCommunity/SmartThingsPublic pull request #1430
Opened 2016-11-06 14:48 UTC by skt123

@jackchi @ShunmugaSundar 
Tested with WeMo LED Bulb. Please review and merge

2016-11-07 16:21 UTC, jackchi requested changes

2016-11-07 16:21 UTC, jackchi commented on devicetypes/smartthings/zigbee-dimmer.src/README.md
> +* [Troubleshooting:](https://support.smartthings.com/hc/en-us/articles/204259040-Belkin-WeMo-LED-Bulb-F7C033-)
Let's add device names for links to troubleshooting

2016-11-08 05:51 UTC, skt123 commented on devicetypes/smartthings/zigbee-dimmer.src/README.md
> +* [Troubleshooting:](https://support.smartthings.com/hc/en-us/articles/204259040-Belkin-WeMo-LED-Bulb-F7C033-)
Yeah, that's better. I have added the device name for the links.

2016-11-08 06:18 UTC, jackchi approved these changes
👍

2016-11-08 06:18 UTC, merged