Added Health Check Implementation for following Osram RT5/6 Tunable White
SmartThingsCommunity/SmartThingsPublic pull request #1431
Opened 2016-11-07 12:41 UTC by skt123

2016-11-07 16:25 UTC, jackchi requested changes

2016-11-07 16:25 UTC, jackchi commented on devicetypes/smartthings/zigbee-white-color-temperature-bulb.src/README.md
> +* [Troubleshooting:](https://www.smartthings.com/works-with-smartthings/light-bulbs/osram-lightify-rt56-tunable-white)
Let's add individual device names

2016-11-07 16:25 UTC, jackchi commented on devicetypes/smartthings/zigbee-white-color-temperature-bulb.src/README.md
> +* [Osram RT5/6 Tunable White](https://www.smartthings.com/works-with-smartthings/light-bulbs/osram-lightify-rt56-tunable-white)
In `zigbee-white-color-temperature-bulb.groovy`, let's change the devoiceJoinName so it matches to the WWST names

2016-11-08 05:51 UTC, skt123 commented on devicetypes/smartthings/zigbee-white-color-temperature-bulb.src/README.md
> +* [Troubleshooting:](https://www.smartthings.com/works-with-smartthings/light-bulbs/osram-lightify-rt56-tunable-white)
Yeah, that's better. I have added the device name for the links.

2016-11-08 05:52 UTC, skt123 commented on devicetypes/smartthings/zigbee-white-color-temperature-bulb.src/README.md
> +* [Osram RT5/6 Tunable White](https://www.smartthings.com/works-with-smartthings/light-bulbs/osram-lightify-rt56-tunable-white)
Updated the deviceJoinName.

2016-11-08 06:17 UTC, jackchi approved these changes

2016-11-08 06:17 UTC, merged