[CHF-455] Implementation of HealthCheck for Leviton Universal Dimmer DZMX1-LZ (Z-wave)
SmartThingsCommunity/SmartThingsPublic pull request #1433
Opened 2016-11-07 13:41 UTC by parijatdas

1. Added the fingerprint of Leviton Universal Dimmer DZMX1-LZ (Z-wave) with the manufacturer, product code and model number obtained from the raw description after pairing.
2. Modified the deviceJoinName accordingly.
3. We've tested the checkInterval duration and the device is marked OFFLINE within the stipulated time.
4. Modified the README.md file accordingly.
@jackchi @ShunmugaSundar Please check and merge the changes.

2016-11-07 16:34 UTC, jackchi requested changes

2016-11-07 16:34 UTC, jackchi commented on devicetypes/smartthings/zwave-dimmer-switch-generic.src/README.md
> +A Category C5 Leviton Plug-in Lamp Dimmer Module (DZPA1-1LW) (Z-wave) and Leviton Universal Dimmer (DZMX1-LZ) (Z-Wave) polled by the hub.
Let's remove `Category 5` for now

2016-11-07 16:34 UTC, jackchi commented on devicetypes/smartthings/zwave-dimmer-switch-generic.src/README.md
> +* [Leviton Universal Dimmer (DZMX1-LZ)](http://www.leviton.com/OA_HTML/ProductDetail.jsp?partnumber=DZMX1-1LZ)
Should we use the WWST link? https://www.smartthings.com/works-with-smartthings/switches-and-dimmers/leviton-universal-dimmer

2016-11-08 03:42 UTC, parijatdas commented on devicetypes/smartthings/zwave-dimmer-switch-generic.src/README.md
> +* [Leviton Universal Dimmer (DZMX1-LZ)](http://www.leviton.com/OA_HTML/ProductDetail.jsp?partnumber=DZMX1-1LZ)
Yeah that's better. I've changed it.

2016-11-08 03:43 UTC, parijatdas commented on devicetypes/smartthings/zwave-dimmer-switch-generic.src/README.md
> +A Category C5 Leviton Plug-in Lamp Dimmer Module (DZPA1-1LW) (Z-wave) and Leviton Universal Dimmer (DZMX1-LZ) (Z-Wave) polled by the hub.
Removed Category.

2016-11-08 06:16 UTC, jackchi approved these changes

2016-11-08 06:16 UTC, merged