DVCSMP-2425 - LIFX Exceptions
SmartThingsCommunity/SmartThingsPublic pull request #1662
Opened 2017-02-11 00:37 UTC by juano2310

2017-02-13 19:36 UTC, marstorp requested changes
Please add a comment explaining the reason for deletion of child devices and the consequences for failing to delete it.

2017-02-13 19:51 UTC, juano2310 commented
The reason the implementation is trying to delete this bulb is because it is not longer connected to the LIFX location. It is failing because the child device it is still connected to a SmartApp and it is preventing it from being deleted causing an exception. Adding the try will prevent this exception from happening. 
Ideally device health would show to the user that the device is not longer accessible so the user can manage the device either by force deleting it or removing it from the SmartApp.

2017-02-15 23:23 UTC, marstorp approved these changes

2017-02-15 23:23 UTC, marstorp commented
LGTM 👍

2017-02-15 23:24 UTC, merged