DVCSMP-2490 Update generic Z-Wave sensor DTHs
SmartThingsCommunity/SmartThingsPublic pull request #1749
Opened 2017-03-06 05:24 UTC by mckeed

Adds support for NotificationReports to Z-Wave Sensor and more encapsulations to other generic sensor DTHs

2017-09-19 08:42 UTC, dkirker requested changes
Really just some minor things. I guess this overlaps with https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/2315 so that would be the one that you would use?

2017-09-19 08:42 UTC, dkirker commented on devicetypes/smartthings/zwave-motion-sensor.src/zwave-motion-sensor.groovy
> +		state.sec = 1
I noted in the other review, would state.sec = true be more consistent?

2017-09-19 08:42 UTC, dkirker commented on devicetypes/smartthings/zwave-sensor.src/zwave-sensor.groovy
> +		state.sec = 1
Same as above.

2017-09-20 19:34 UTC, mckeed commented
I've moved these changes to #2315

2017-09-20 19:34 UTC, closed without merging