[WWST-5161] Added and integrated Everspring Wall Switch
SmartThingsCommunity/SmartThingsPublic pull request #17872
Opened 2020-01-10 14:03 UTC by ZWozniakS

@greens Could you please review?
@KKlimczukS @PKacprowiczS @MGoralczykS

2020-01-10 18:53 UTC, greens requested changes
the child buttons also have a line where we set their supported button values. You'll need to change that as well.

2020-01-13 11:08 UTC, ZWozniakS commented
Of course, I've done it IDE but forgot to add here, sorry. Done!

2020-01-14 01:43 UTC, dkirker approved these changes

2020-01-14 20:57 UTC, greens approved these changes

2020-01-14 20:57 UTC, merged