DTH for WWST-6400 - Sercomm Door and Window Sensor - SZ-DWS04
SmartThingsCommunity/SmartThingsPublic pull request #17913
Opened 2020-01-13 09:52 UTC by rajendrasamsung

DTH for WWST-6400 - Sercomm Door and Window Sensor - SZ-DWS04

Added FP:
fingerprint profileId: "0104,0402", inClusters: "0000,0001,0003,0402,0500,0020,0B05", outClusters: "0003,0019", manufacturer: "Sercomm Corp.", model: "SZ-DWS04", deviceJoinName: "Door Window Sensor"

Please review & approve PR.

2020-01-13 15:57 UTC, tpmanley commented on devicetypes/smartthings/smartsense-multi-sensor.src/smartsense-multi-sensor.groovy
> +		fingerprint profileId: "0104,0402", inClusters: "0000,0001,0003,0402,0500,0020,0B05", outClusters: "0003,0019", manufacturer: "Sercomm Corp.", model: "SZ-DWS04", deviceJoinName: "Door Window Sensor
The `profileId` is not required but if present it should only have one value which is typically `0104`

2020-01-13 15:57 UTC, tpmanley commented on devicetypes/smartthings/smartsense-multi-sensor.src/smartsense-multi-sensor.groovy
> +		fingerprint profileId: "0104,0402", inClusters: "0000,0001,0003,0402,0500,0020,0B05", outClusters: "0003,0019", manufacturer: "Sercomm Corp.", model: "SZ-DWS04", deviceJoinName: "Door Window Sensor
Please double check the `deviceJoinName`. According to the ticket it should include `Sercomm`.

2020-01-13 16:01 UTC, tpmanley commented
I have some questions about the accelerometer functionality but I left a comment on the ticket.

2020-01-20 06:28 UTC, ganeshasprabhu requested changes
fingerprint inClusters: "0000,0001,0003,0402,0500,0020,0B05", outClusters: "0019", manufacturer: "Sercomm Corp.", model: "SZ-DWS04", deviceJoinName: "Sercomm Door Window Sensor"

2020-01-20 08:49 UTC, rajendrasamsung commented
Closing this PR. Accelerator sensor is not supported for this device. I will raise new PR  to the file
smartsense-open-closed-sensor.groovy

fingerprint inClusters: "0000,0001,0003,0402,0500,0020,0B05", outClusters: "0019", manufacturer: "Sercomm Corp.", model: "SZ-DWS04", deviceJoinName: "Sercomm Door Window Sensor", mnmn: "SmartThings", vid: "generic-contact"

2020-01-20 08:49 UTC, closed without merging