[CHF-568] Health Check keen-home-smart-vent
SmartThingsCommunity/SmartThingsPublic pull request #1815
Opened 2017-03-22 12:55 UTC by pchomal

Health Check keen-home-smart-vent

2017-03-22 12:55 UTC, pchomal commented
@jackchi @ShunmugaSundar 

Please review & merge

2017-03-23 15:49 UTC, jackchi requested changes

2017-03-23 15:49 UTC, jackchi commented on devicetypes/keen-home/keen-home-smart-vent.src/keen-home-smart-vent.groovy
> +    return configCmds + zigbee.onOffConfig(0, 300) + refresh()
The `5 minutes` reporting interval was a requirement set by VD (TV-Project). We no longer have these restraints. Let's use the default reporting `onOffConfig()` interval specified in: 
https://github.com/PhysicalGraph/appengine-zigbee/blob/master/src/main/groovy/physicalgraph/zigbee/Zigbee.groovy#L507
Which is `10min`.

2017-03-24 18:03 UTC, pchomal commented
@jackchi 

I made changes for  keen home smart vent, removing the explicit setting of max report time as you said.
Then while going through its events saw that the temperature & pressure (especially) cluster are reporting CHANGES every minute.
It doesn't seem to be a reporting device, but one which sends status change events regularly.
So how should this be handled? And what should be the checkInterval for this case?

2017-03-24 21:11 UTC, jackchi commented
Can you point out the line where it is sending a report for temp/pressure every minute? I only see the `bind` command.

2017-03-24 21:15 UTC, jackchi requested changes
1. Change to default onOffConfig() 
2. Implement `ping` with `refresh`
3. Remove 2 different `checkInterval` in parse()
4. `checkInterval` based on default onOffConfig() = 10 *2 + 2=  22min

2017-03-24 21:15 UTC, jackchi commented on devicetypes/keen-home/keen-home-smart-vent.src/keen-home-smart-vent.groovy
> +    return zigbee.onOffRefresh()
We can call `refresh()` here.

2017-03-27 09:21 UTC, pchomal commented
@jackchi 
Made the requested changes.

2017-03-27 16:49 UTC, jackchi commented on devicetypes/keen-home/keen-home-smart-vent.src/keen-home-smart-vent.groovy
> -        "zdo bind 0x${device.deviceNetworkId} 1 1 0x0006 {${device.zigbeeId}} {}", "delay 500",
Is this bind cluster cmd suppose to be deleted?

2017-03-27 17:25 UTC, pchomal commented on devicetypes/keen-home/keen-home-smart-vent.src/keen-home-smart-vent.groovy
> -        "zdo bind 0x${device.deviceNetworkId} 1 1 0x0006 {${device.zigbeeId}} {}", "delay 500",
This bind cluster corresponds to onOff cluster.
So as I'm using the wrapper, `zigbee.onOffConfig()`, so deleted that bind cluster cmd.

2017-03-27 17:42 UTC, jackchi approved these changes

2017-03-27 17:42 UTC, jackchi commented
👍

2017-03-27 17:43 UTC, merged