[CHF-572] Added Health Check Implementation for Zen Thermostat.
SmartThingsCommunity/SmartThingsPublic pull request #1816
Opened 2017-03-22 13:08 UTC by skt123

@jackchi @ShunmugaSundar 
Added Health check for Zen Thermostat with checkInterval of 12 mins.
Please review and merge.

2017-03-23 15:59 UTC, jackchi requested changes

2017-03-23 15:59 UTC, jackchi commented on devicetypes/zenwithin/zen-thermostat.src/zen-thermostat.groovy
> +          "zcl global send-me-a-report 0x201 0 0x29 0 300 {3200}",
We do not want to change the `minReportTime` attribute in this zcl cmd. 
FYI:
`minReportTime - Minimum number of seconds between reports`

2017-03-23 16:02 UTC, jackchi commented on devicetypes/zenwithin/zen-thermostat.src/zen-thermostat.groovy
> +          "zcl global send-me-a-report 0x201 0 0x29 0 300 {3200}",
https://github.com/PhysicalGraph/appengine-zigbee/blob/master/src/main/groovy/physicalgraph/zigbee/Zigbee.groovy#L348

2017-03-24 14:15 UTC, skt123 commented
@jackchi 
Made the required changes. Please check.

2017-03-24 21:18 UTC, jackchi approved these changes
👍

2017-03-24 21:18 UTC, merged