[CHF-562] Health Check zwave-door-window-sensor
SmartThingsCommunity/SmartThingsPublic pull request #1817
Opened 2017-03-22 13:16 UTC by pchomal

Health Check Z-Wave door window sensor with readme.

2017-03-22 13:16 UTC, pchomal commented
@jackchi @ShunmugaSundar 

Please review & merge

2017-03-23 15:17 UTC, skt123 requested changes

2017-03-23 15:17 UTC, skt123 commented on devicetypes/smartthings/zwave-door-window-sensor.src/zwave-door-window-sensor.groovy
> +def ping() {
Sleepy device, so defining ping() is immaterial.

2017-03-23 15:18 UTC, skt123 commented on devicetypes/smartthings/zwave-door-window-sensor.src/zwave-door-window-sensor.groovy
> +def ping() {
@jackchi Please confirm.

2017-03-23 16:35 UTC, jackchi commented on devicetypes/smartthings/zwave-door-window-sensor.src/zwave-door-window-sensor.groovy
> +def ping() {
Are you able to get any event out of this device with a `batteryGet()`?
My intuition is that it is sleepy and won't respond.

2017-03-27 16:52 UTC, jackchi commented on devicetypes/smartthings/zwave-door-window-sensor.src/zwave-door-window-sensor.groovy
> +def ping() {
One way to check this is thru Sumo Logic Device-Watch logs. If battery didn't change on graph, it won't result in an event that is visible. 
`_sourceCategory=app-production _source=devicewatch "<deviceId>"`

2017-03-27 17:00 UTC, jackchi commented on devicetypes/smartthings/zwave-door-window-sensor.src/zwave-door-window-sensor.groovy
> +def ping() {
@skt123 Just got word from @mckeed that this is a Sleepy device. 
Do not implement `ping` here.

2017-03-27 17:06 UTC, jackchi requested changes
Please make changes before Tuesday

2017-03-27 17:06 UTC, jackchi commented on devicetypes/smartthings/zwave-door-window-sensor.src/zwave-door-window-sensor.groovy
> +	sendEvent(name: "checkInterval", value: 2 * 15 * 60 + 2 * 60, displayed: false, data: [protocol: "zwave", hubHardwareId: device.hub.hardwareID])
Should be similar to `fibaro-motion-sensor`. Should be set to 8 hrs and 2 minutes

2017-03-27 17:34 UTC, pchomal commented
@jackchi 
Made the requested changes.

2017-03-27 17:43 UTC, jackchi approved these changes
LGTM 👍

2017-03-27 17:43 UTC, merged