[CHF-577] Added Health Check Implementation for Spruce Controller.
SmartThingsCommunity/SmartThingsPublic pull request #1818
Opened 2017-03-22 13:58 UTC by skt123

@jackchi @ShunmugaSundar 
Added Health check for Spruce Controller with checkInterval of 12 mins.
Please review and merge.

2017-03-23 16:36 UTC, jackchi requested changes

2017-03-23 16:36 UTC, jackchi commented on devicetypes/plaidsystems/spruce-controller.src/spruce-controller.groovy
> +    return configCmds + zigbee.onOffConfig(0, 300) + rain() + manual()
Let's use default `onOffConfig` reporting interval

2017-03-27 16:54 UTC, jackchi commented
Please make the following changes:

1. Change to default onOffConfig()
2. Implement ping with refresh
3. Remove 2 different checkInterval in parse()
4. checkInterval based on default onOffConfig() = 10 *2 + 2= 22min

2017-03-27 18:16 UTC, skt123 commented
@jackchi 
Made the changes. Please check

2017-03-27 18:53 UTC, jackchi approved these changes
LGTM! 👍

2017-03-27 18:53 UTC, merged