[CHF-571] Added Health Check Implementation for EcoNet Vent.
SmartThingsCommunity/SmartThingsPublic pull request #1819
Opened 2017-03-22 14:19 UTC by skt123

@jackchi @ShunmugaSundar 
Added Health check for Zen Thermostat with checkInterval of 32 mins.
Please review and merge.

2017-03-23 16:41 UTC, jackchi requested changes
Other than color value, it's good.

2017-03-23 16:41 UTC, jackchi commented on devicetypes/smartthings/econet-vent.src/econet-vent.groovy
> +			state "on", action:"switch.off", icon:"st.vents.vent-open-text", backgroundColor:"#53a7c0"
Rebase from master again. This value should be `00adc`.

2017-03-24 12:42 UTC, skt123 commented
@jackchi Removed color value change.
Please check.

2017-03-24 21:17 UTC, jackchi approved these changes
LGTM 👍

2017-03-27 17:44 UTC, merged