[CHF-569] Health Check zwave-water-valve
SmartThingsCommunity/SmartThingsPublic pull request #1834
Opened 2017-03-27 20:46 UTC by parijatdas

1. Added health check for Leak Intelligence Leak Gopher Water Shutoff Valve.
2. 'checkInterval' is kept at 32min.
3. Ping is implemented using refresh().
4. Added the fingerprint of the Leak Intelligence Leak Gopher Water Shutoff Valve with the manufacturer and product code obtained from the raw description after pairing.
5. We've tested the checkInterval duration and the devices are marked OFFLINE within the stipulated time.
6. Added the README.md file.
@jackchi @ShunmugaSundar Please check and merge the changes.

2017-03-28 17:28 UTC, jackchi requested changes

2017-03-28 17:28 UTC, jackchi commented on devicetypes/smartthings/zwave-water-valve.src/zwave-water-valve.groovy
> +	runEvery15Minutes("healthPoll")
Let's use the Z-Wave reporting interval cmd class:
`zwave.wakeUpV2.wakeUpIntervalSet(...)`

2017-03-30 18:13 UTC, mckeed commented on devicetypes/smartthings/zwave-water-valve.src/zwave-water-valve.groovy
> +	runEvery15Minutes("healthPoll")
WakeUp is only available on sleepy devices.

We should just get rid of this healthPoll thing. The whole point of ping() was for devices like this that don't check in regularly or need to be polled for status.

2017-05-15 21:49 UTC, jackchi commented on devicetypes/smartthings/zwave-water-valve.src/zwave-water-valve.groovy
>  def updated() {
Let's have `checkInterval` in installed() method too.

2017-05-16 06:57 UTC, parijatdas commented on devicetypes/smartthings/zwave-water-valve.src/zwave-water-valve.groovy
>  def updated() {
`checkInterval` event put in installed() method as well.

2017-05-18 00:05 UTC, jackchi approved these changes

2017-05-18 00:05 UTC, merged