MSA-2084: Spruce Sensor DTH new model and health check
SmartThingsCommunity/SmartThingsPublic pull request #2148
Opened 2017-07-06 20:22 UTC by natec007

Submitting 'Spruce Sensor DTH new model and health check' for publication

2017-07-06 21:15 UTC, jackchi commented
Is this DTH "pingable()" - meaning, that we can contact the device and device would generate an event in the parse() method?

2017-07-06 21:16 UTC, jackchi requested changes
1. Take out `checkInterval` from custom attribute
2. Add `sendEvent("checkInterval")` to both updated/installed
3. Can this device be pinged?

2017-07-06 21:16 UTC, jackchi commented on devicetypes/plaidsystems/spruce-sensor.src/spruce-sensor.groovy
> +        attribute "checkInterval", "string"
No need to add `checkInterval` here. It's actually included as a `NUMBER` in the Capbility `Health Check`

2017-07-06 21:16 UTC, jackchi commented on devicetypes/plaidsystems/spruce-sensor.src/spruce-sensor.groovy
> +    sendEvent(name: "checkInterval", value: 1 * 60 * 60 + 2 * 60, displayed: false, data: [protocol: "zigbee", hubHardwareId: device.hub.hardwareID])
Let's put this `sendEvent("checkInterval")` in both `installed()` & `updated()`

2017-07-06 21:29 UTC, natec007 commented on devicetypes/plaidsystems/spruce-sensor.src/spruce-sensor.groovy
> +    sendEvent(name: "checkInterval", value: 1 * 60 * 60 + 2 * 60, displayed: false, data: [protocol: "zigbee", hubHardwareId: device.hub.hardwareID])
Its a sleepy ZigBee device, so can't be pinged except when awake.

2017-07-06 21:33 UTC, jackchi commented on devicetypes/plaidsystems/spruce-sensor.src/spruce-sensor.groovy
> +    sendEvent(name: "checkInterval", value: 1 * 60 * 60 + 2 * 60, displayed: false, data: [protocol: "zigbee", hubHardwareId: device.hub.hardwareID])
So how often does this device check-in (generate an event) when idle? Currently if our platform doesn't hear from this device in 62min (your checkInterval value) it'll mark it `OFFLINE`

2017-07-06 21:38 UTC, natec007 commented on devicetypes/plaidsystems/spruce-sensor.src/spruce-sensor.groovy
> +    sendEvent(name: "checkInterval", value: 1 * 60 * 60 + 2 * 60, displayed: false, data: [protocol: "zigbee", hubHardwareId: device.hub.hardwareID])
It pings the coordinator (hub) every 10 mins but reports data between 10-120mins

2017-07-07 19:13 UTC, jackchi approved these changes
Everything looks good.

2017-07-07 19:13 UTC, jackchi commented on devicetypes/plaidsystems/spruce-sensor.src/spruce-sensor.groovy
> +    sendEvent(name: "checkInterval", value: 1 * 60 * 60 + 2 * 60, displayed: false, data: [protocol: "zigbee", hubHardwareId: device.hub.hardwareID])
👍

2017-07-07 19:14 UTC, merged