[DVCSMP-2807] Onboard Fibaro Wall Plug ZW5
SmartThingsCommunity/SmartThingsPublic pull request #2206
Opened 2017-08-01 12:07 UTC by parijatdas

Onboarding Fibaro Wall Plug ZW5.

@jackchi @mckeed @ShunmugaSundar Please review and merge the changes.

2017-08-07 19:26 UTC, jackchi requested changes
Tile changes

2017-08-07 19:26 UTC, jackchi commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +	tiles {
@parijatdas Please use multiAttribute tiles to get 2x2 look. 
![201708080025720_pymc4cbb](https://user-images.githubusercontent.com/255235/29042369-890e9602-7b6b-11e7-8c4c-7744594d5212.jpg) that's the older view

2017-08-08 10:09 UTC, parijatdas commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +	tiles {
I've used multi-attribute tile and made the necessary changes. Please check.

2017-09-06 09:19 UTC, dkirker commented
@jackchi  Regarding https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/2282 I am pretty sure that this is going to be the proper PR. I will message you about this.

2017-09-07 19:33 UTC, jackchi commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +		createEvent(name: "power", value: Math.round(cmd.scaledMeterValue), unit: "W")
See ICP-1637
https://smartthings.atlassian.net/browse/ICP-1637

2017-09-08 19:21 UTC, jackchi approved these changes

2017-09-18 09:04 UTC, dkirker commented
I would like to cross-check a few things before merging this. Please hold off.

2017-09-21 10:05 UTC, dkirker requested changes
@parijatdas Could you please make the requested revisions ASAP? Thanks!

2017-09-21 10:05 UTC, dkirker commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +		capability "Polling"
If we are implementing the Polling capability then we will need the poll() command implemented as well.

2017-09-21 10:05 UTC, dkirker commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +		fingerprint mfr:"0072", prod:"0501", model:"0F06", deviceJoinName: "FIBARO Wall Plug ZW5"
Please update the deviceJoinName to "Fibaro Wall Plug ZW5"

Also, please add the fingerprint:
```groovy
fingerprint mfr: "010F", prod: "0602", model: "1001", deviceJoinName: "Fibaro Wall Plug ZW5"
```

2017-09-21 10:05 UTC, dkirker commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +		multiAttributeTile(name:"FGWP", type:"lighting", width:6, height:4) {//with generic type secondary control text is not displayed in Android app
Since we are using this as a generic DTH, let's replace "FGWP" with "lighting"

2017-09-21 10:05 UTC, dkirker commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +		details(["FGWP", "energy", "reset", "refresh"])
Let's replace "FGWP" with "lighting" here and the line above. See previous comment for why.

2017-09-21 10:05 UTC, dkirker commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +					descriptionText: "FGK failed to complete the network security key exchange. If you are unable to receive data from it, you must remove it from your network and add it again.",
Please replace "FGK" with "Switch"

2017-09-21 10:05 UTC, dkirker commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +	log.debug "Parsing '${description}'"
Please add below the debug

def result

2017-09-21 10:05 UTC, dkirker commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +			zwaveEvent(cmd)
Please change to:

result = zwaveEvent(cmd)

2017-09-21 10:05 UTC, dkirker commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +}
Please change line 116 to:
```groovy
    result
}
```

2017-09-21 10:05 UTC, dkirker commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +	cmds += zwave.versionV1.versionGet()
Please remove manufacturerSpecificGet and versionGet, we now get those and they are accessible in zwInfo.

2017-09-21 10:13 UTC, dkirker commented on devicetypes/smartthings/zwave-metering-switch-secure.src/zwave-metering-switch-secure.groovy
> +		capability "Polling"
A good poll would be

```groovy
def poll() {
	refresh()
}
```

:P

2017-09-21 10:16 UTC, ShunmugaSundar commented
@dkirker , Parijat is leaving the Samsung today. Is it ok if @skt123 can raise a separate pull request for these changes?

2017-09-21 10:20 UTC, dkirker commented
@ShunmugaSundar Best wishes to @parijatdas ! Yes, @skt123 can make a seperate PR, or I can go ahead and do that. I just made the edits so that I could ask Poland to test it while the PR was being created. It will take me a couple of minutes.

Either way is fine with me! Whichever you would prefer.

2017-09-21 10:25 UTC, ShunmugaSundar commented
@dkirker if possible , It would be better if you can make separate PR as @skt123 would need time to understand the changes and make the PR.

2017-09-21 10:26 UTC, dkirker commented
@ShunmugaSundar I will do that, thanks. I do recommend that @skt123 still look over and understand the changes for future work. Thanks! :)

2017-09-21 10:28 UTC, ShunmugaSundar commented
@dkirker Thanks a lot. Sure @skt123 will have a look

2017-09-21 10:32 UTC, dkirker commented
Thanks all! Closing this PR. A new PR is coming shortly.

2017-09-21 10:32 UTC, closed without merging

2017-09-21 10:44 UTC, dkirker commented
Please see #2353 for future work on this