Add fingerprint for Aurora AU-A1ZB320 device. Add device to README file.
SmartThingsCommunity/SmartThingsPublic pull request #2805
Opened 2018-02-15 14:50 UTC by MMateusiakS

2018-02-20 22:50 UTC, greens requested changes
Can you upload again without converting the whitespace? It makes it difficult to tell what was changed.

2018-02-21 09:39 UTC, MMateusiakS commented
@greens sure, changes added.

2018-02-22 00:31 UTC, greens approved these changes

2018-02-22 00:33 UTC, greens approved these changes
Looks good, but we'll wait until we hear back from cert before merging.

2018-03-19 18:53 UTC, merged