[WWST-172] ecobee-add-switch-20180307
SmartThingsCommunity/SmartThingsPublic pull request #2875
Opened 2018-03-07 22:45 UTC by twack

2018-03-08 19:08 UTC, bflorian requested changes
Besides the specific comments, I'm really confused as to how polling is working here, with poll, pollChild, pollChildren, and pollHandler. We may want to make it a separate PR but I think we should refactor this to not use the built in device poll() capability (which is being deprecated anyway) and have the service manager control polling of all the devices.

2018-03-08 19:08 UTC, bflorian commented on devicetypes/smartthings/ecobee-switch.src/ecobee-switch.groovy
> +}
I hate to be picky but let's not have messed up whitespace in brand new code. We officially are supposed to use tabs but I won't complain about four spaces.

2018-03-08 19:08 UTC, bflorian commented on smartapps/smartthings/ecobee-connect.src/ecobee-connect.groovy
> +    delete.each {
I'm not seeing where `delete` is set any longer, and for that matter, why we need to do this at all. Isn't the only reason for having this method to update the settings when a device is deleted

2018-03-08 19:08 UTC, bflorian commented on smartapps/smartthings/ecobee-connect.src/ecobee-connect.groovy
> +    	return
Rather than assume the platform behavior of deleting the service manager when the last device is deleted I think it would be safer in this case to just update the settings to an empty list and let the platform do (or not do) what it wants with the service manager.

2018-03-09 16:07 UTC, twack commented on devicetypes/smartthings/ecobee-switch.src/ecobee-switch.groovy
> +}
My editors show correctly. I will make sure that I change editor defaults. Updated file to tab correctly.

2018-03-09 16:08 UTC, twack commented on smartapps/smartthings/ecobee-connect.src/ecobee-connect.groovy
> +    	return
Updated to suggested method

2018-03-09 16:11 UTC, twack commented
ticket for refactor of polling method:
https://smartthings.atlassian.net/browse/WWST-202
Ecobee will be updating their service capabilities to publish events. That will be a good time to implement the preferred polling methodology.

2018-03-20 16:51 UTC, bflorian approved these changes

2018-03-20 16:51 UTC, merged