[ICP-13017] Settings change for Stelpro Ki Zigbee Thermostat
SmartThingsCommunity/SmartThingsPublic pull request #28828
Opened 2020-04-21 10:00 UTC by PKacprowiczS

This is also for ICP-13019
@greens @KKlimczukS @MGoralczykS @ZWozniakS @MWierzbinskaS @BJanuszS

2020-04-21 19:58 UTC, greens approved these changes

2020-04-23 04:07 UTC, dkirker commented
I left a comment on the ticket. Another thing to note: The Stelpro integrations all generally behave the same way. I would highly recommend that whatever changes are made to one are made to all for consistency.

While the updating of the outdoor preference looks good, I recommend leaving the "display more detailed operating state updates" preference if it behaves the same in the new app as it does in Classic.

2020-04-23 04:20 UTC, dkirker requested changes

2020-04-23 04:20 UTC, dkirker commented on devicetypes/stelpro/stelpro-ki-zigbee-thermostat.src/stelpro-ki-zigbee-thermostat.groovy
>  				// don't show them. Otherwise, don't show them more frequently than 30 seconds.
If we chose to remove this preference, this comment will need to be updated to reflect that. If we only change the preference text, then this comment can stay as-is.

2020-06-05 08:24 UTC, closed without merging