[DVCSMP-3648] Onboarding Fibaro CO Sensor ZW5
SmartThingsCommunity/SmartThingsPublic pull request #2886
Opened 2018-03-09 19:08 UTC by sagar-trility

2018-05-24 18:39 UTC, greens commented on devicetypes/fibargroup/fibaro-co-sensor-zw5.src/fibaro-co-sensor-zw5.groovy
> +        attribute "temperatureAlarm", "string"
we should probably convert this to the "Temperature Alarm" capability:

https://github.com/SmartThingsCommunity/SmartThingsCapabilities/blob/master/capabilities/temperature-alarm.src/temperature-alarm.yml

2018-05-24 18:42 UTC, greens commented on devicetypes/fibargroup/fibaro-co-sensor-zw5.src/fibaro-co-sensor-zw5.groovy
> +        attribute "temperatureAlarm", "string"
"clear" will need to be the default state and "heat" will have to replace "overheat"

2018-05-24 18:47 UTC, greens commented on devicetypes/fibargroup/fibaro-co-sensor-zw5.src/fibaro-co-sensor-zw5.groovy
> +        fingerprint deviceId: "0x0701", inClusters:"0x5E,0x59,0x73,0x80,0x22,0x56,0x31,0x98,0x7A,0x5A,0x85,0x84,0x71,0x70,0x8E,0x9C,0x86,0x72"
this fingerprint is redundant

2018-05-24 18:47 UTC, greens requested changes
May want to go ahead and convert to tabs as well

2018-05-25 17:25 UTC, greens commented on devicetypes/fibargroup/fibaro-co-sensor-zw5.src/fibaro-co-sensor-zw5.groovy
> +    definition (name: "Fibaro CO Sensor ZW5", namespace: "FibarGroup", author: "Fibar Group") {
please add `ocfDeviceType: "x.com.st.d.sensor.smoke"` so that the correct icon is displayed in OneApp

2018-06-04 14:50 UTC, sagar-trility commented
@greens PR has been updated. Please review. Thank You.

2018-06-05 18:11 UTC, greens commented on devicetypes/fibargroup/fibaro-co-sensor-zw5.src/fibaro-co-sensor-zw5.groovy
> +		attribute "temperatureAlarm", "string"
Please convert to use the "Heat Alarm" capability.

2018-06-05 18:11 UTC, greens commented on devicetypes/fibargroup/fibaro-co-sensor-zw5.src/fibaro-co-sensor-zw5.groovy
> +		fingerprint deviceId: "0x0701", inClusters:"0x5E,0x59,0x73,0x80,0x22,0x56,0x31,0x98,0x7A,0x5A,0x85,0x84,0x71,0x70,0x8E,0x9C,0x86,0x72"
still redundant

2018-06-05 18:22 UTC, sagar-trility commented
@greens PR is updated.

2018-06-05 22:16 UTC, greens commented on devicetypes/fibargroup/fibaro-co-sensor-zw5.src/fibaro-co-sensor-zw5.groovy
> +private List intToParam(Long value, Integer size = 1) {
method can be removed since it's no longer used.

2018-06-05 22:17 UTC, greens commented on devicetypes/fibargroup/fibaro-co-sensor-zw5.src/fibaro-co-sensor-zw5.groovy
> +def ping() {
If the device is sleepy (sends us a wakeup notification every X hours), it won't respond to these commands.

2018-06-06 12:28 UTC, sagar-trility commented
@greens Changes have been made.

2018-06-06 22:20 UTC, greens approved these changes

2018-06-06 22:23 UTC, greens approved these changes

2018-06-06 22:23 UTC, merged