[DVCSMP-3649] Onboarding Fibaro Motion Sensor ZW5
SmartThingsCommunity/SmartThingsPublic pull request #2888
Opened 2018-03-09 19:31 UTC by sagar-trility

2018-05-25 18:15 UTC, greens commented on devicetypes/fibargroup/fibaro-motion-sensor-zw5.src/fibaro-motion-sensor-zw5.groovy
> +    definition (name: "Fibaro Motion Sensor ZW5", namespace: "FibarGroup", author: "Fibar Group") {
Keep the ocfDeviceType. OneApp uses that field fro determining icons.

2018-05-25 18:15 UTC, greens commented on devicetypes/fibargroup/fibaro-motion-sensor-zw5.src/fibaro-motion-sensor-zw5.groovy
> +        fingerprint deviceId: "0x0701", inClusters: "0x5E, 0x20, 0x86, 0x72, 0x5A, 0x59, 0x85, 0x73, 0x84, 0x80, 0x71, 0x56, 0x70, 0x31, 0x8E, 0x22, 0x30, 0x9C, 0x98, 0x7A"
redundant

2018-05-25 18:17 UTC, greens commented on devicetypes/fibargroup/fibaro-motion-sensor-zw5.src/fibaro-motion-sensor-zw5.groovy
> +            tileAttribute("device.multiStatus", key:"SECONDARY_CONTROL") {
custom attributes should be declared up at the top using the `attribute` function

2018-05-25 18:21 UTC, greens commented on devicetypes/fibargroup/fibaro-motion-sensor-zw5.src/fibaro-motion-sensor-zw5.groovy
> +	configure()
whitespace

2018-05-25 18:24 UTC, greens commented on devicetypes/fibargroup/fibaro-motion-sensor-zw5.src/fibaro-motion-sensor-zw5.groovy
> +	sendEvent(name: "checkInterval", value: 1920, displayed: false, data: [protocol: "zwave", hubHardwareId: device.hub.hardwareID])
if this is a sleepy device, this interval should be 8 hours + 2 minutes.

2018-05-25 18:25 UTC, greens commented on devicetypes/fibargroup/fibaro-motion-sensor-zw5.src/fibaro-motion-sensor-zw5.groovy
> +	configure()
this is also called in `updated()`. It will result in the same poll being made twice.

2018-05-25 18:26 UTC, greens commented on devicetypes/fibargroup/fibaro-motion-sensor-zw5.src/fibaro-motion-sensor-zw5.groovy
> +def configure() {
if the calls in this method aren't actually configuring anything, they shouldn't be in `configure`

2018-05-25 18:27 UTC, greens commented on devicetypes/fibargroup/fibaro-motion-sensor-zw5.src/fibaro-motion-sensor-zw5.groovy
> +private List intToParam(Long value, Integer size = 1) {
same comment as before. You should just be able to pass the value as `scaledConfigurationValue` instead of calling this here

2018-05-25 18:28 UTC, greens requested changes
A lot of similar issues as other Fibaro DTHs.

2018-06-07 14:47 UTC, sagar-trility commented
@greens PR is ready for preview.

2018-06-07 21:23 UTC, greens commented on devicetypes/fibargroup/fibaro-motion-sensor-zw5.src/fibaro-motion-sensor-zw5.groovy
> +		fingerprint deviceId: "0x0701", inClusters: "0x5E, 0x20, 0x86, 0x72, 0x5A, 0x59, 0x85, 0x73, 0x84, 0x80, 0x71, 0x56, 0x70, 0x31, 0x8E, 0x22, 0x30, 0x9C, 0x98, 0x7A", outClusters: ""
We wanted to keep the less-specific fingerprint (fewer command classes listed).

2018-06-08 12:08 UTC, sagar-trility commented
@greens PR is ready for review.

2018-06-08 12:08 UTC, sagar-trility commented on devicetypes/fibargroup/fibaro-motion-sensor-zw5.src/fibaro-motion-sensor-zw5.groovy
> +		fingerprint deviceId: "0x0701", inClusters: "0x5E, 0x20, 0x86, 0x72, 0x5A, 0x59, 0x85, 0x73, 0x84, 0x80, 0x71, 0x56, 0x70, 0x31, 0x8E, 0x22, 0x30, 0x9C, 0x98, 0x7A", outClusters: ""
Fingerprint has been removed.

2018-06-08 20:15 UTC, greens approved these changes

2018-06-08 20:16 UTC, merged