[DVCSMP-3653] On-boarding Fibaro Wall Plug EU ZW5
SmartThingsCommunity/SmartThingsPublic pull request #2954
Opened 2018-03-26 17:46 UTC by sagar-trility

2018-05-24 18:26 UTC, greens commented on devicetypes/fibargroup/fibaro-wall-plug-eu-zw5.src/fibaro-wall-plug-eu-zw5.groovy
> +    definition (name: "Fibaro Wall Plug EU ZW5", namespace: "FibarGroup", author: "Fibar Group") {
add generic ui metadata

2018-05-24 18:27 UTC, greens commented on devicetypes/fibargroup/fibaro-wall-plug-eu-zw5.src/fibaro-wall-plug-eu-zw5.groovy
> +        command "refresh"
replace with "Refresh" capability and add a ping() method

2018-05-24 18:27 UTC, greens commented on devicetypes/fibargroup/fibaro-wall-plug-eu-zw5.src/fibaro-wall-plug-eu-zw5.groovy
> +        fingerprint deviceId: "0x1001", inClusters:"0x5E,0x22,0x59,0x56,0x7A,0x32,0x71,0x73,0x98,0x31,0x85,0x70,0x72,0x5A,0x8E,0x25,0x86"
this fingerprint is redundant due to the more general one below

2018-05-24 18:28 UTC, greens commented on devicetypes/fibargroup/fibaro-wall-plug-eu-zw5.src/fibaro-wall-plug-eu-zw5.groovy
> +    encap(zwave.basicV1.basicSet(value: 255))
we prefer to use hex values here

2018-05-24 18:29 UTC, greens commented on devicetypes/fibargroup/fibaro-wall-plug-eu-zw5.src/fibaro-wall-plug-eu-zw5.groovy
> +    if (device.currentValue("numberOfButtons") != 6) { sendEvent(name: "numberOfButtons", value: 6) }
unused

2018-05-24 18:30 UTC, greens requested changes
also may want to preemptively convert spaces to tabs

2018-06-04 14:41 UTC, sagar-trility commented
@greens Changes have been made. Please can you review the PR. Thank You.

2018-06-05 19:05 UTC, greens approved these changes

2018-06-05 19:07 UTC, merged