[DEVC-597] Add fingerprint for Bosh Radion ZigBee Motion Detector RFDL-ZB-MS to generic Smart Sense Motion Detector DTH.
SmartThingsCommunity/SmartThingsPublic pull request #2964
Opened 2018-03-28 11:32 UTC by ALamchaS

Device seems to work correctly using generic DTH.

According to printed instruction sheet, device reports movement using red LED only once every 3 minutes to preserve battery.

I was quite surprised to find out the same holds true for motion events sent via zigbee.

2018-03-28 20:24 UTC, greens requested changes
Can you double-check the battery reporting code? I think it's pretty non-standard and I'd be surprised if it still worked as expected.

2018-03-29 11:49 UTC, ALamchaS commented
Ok. So it seems Bosch reports raw value 30 for 100%, so I should probably make a manufacturer check to use "old" battery reporting.

2018-04-03 20:08 UTC, greens approved these changes

2018-04-03 20:13 UTC, greens commented
@tpmanley: @ALamchaS 's changes in his last commit around battery reporting look correct to me, but can you double-check that they make sense zigbee-wise?

Olek's comment from the ticket:

> It uses 1 or 2 parallel CR123 batteries.
> That means they should have about 3V when fully charged, and 2V when empty. This seems consistent with raw value 30 report that we get for power configuration cluster attribute 0x0020 when using fresh batteries.

2018-04-03 20:29 UTC, tpmanley approved these changes

2018-04-03 21:03 UTC, merged