[DVCSMP-3697] On-Boarding Fibaro Smoke Sensor ZW5
SmartThingsCommunity/SmartThingsPublic pull request #3013
Opened 2018-04-16 17:05 UTC by sagar-trility

2018-06-05 18:32 UTC, sagar-trility commented
@greens This PR is ready for review as well.

2018-06-05 22:21 UTC, greens commented on devicetypes/smartthings/fibaro-smoke-sensor.src/fibaro-smoke-sensor.groovy
>          attribute "heatAlarm", "enum", ["overheat detected", "clear", "rapid temperature rise", "underheat detected"]
I'd update this to the Temperature Alarm capability that has been defined since this was originally written.

2018-06-05 22:23 UTC, greens commented on devicetypes/smartthings/fibaro-smoke-sensor.src/fibaro-smoke-sensor.groovy
> +    if (zwaveInfo?.mfr == "010F" && zwaveInfo.prod == "0C02"){
I'd move this into it's own function since it's called a couple of times.

2018-06-05 22:29 UTC, greens requested changes
Please also add a generic metadata reference and clean up the whitespace.

2018-06-12 15:40 UTC, sagar-trility commented
@greens Ready for review.

2018-06-12 20:50 UTC, greens approved these changes

2018-06-12 20:51 UTC, merged