[WWST-2447] New DTH for Qubino Flush 1D Relay
SmartThingsCommunity/SmartThingsPublic pull request #30593
Opened 2020-05-08 14:35 UTC by MGoralczykS

I used child DTH's from @BJanuszS PR.

This Qubino supports Qubino Temperature Sensor ZMNHEA1 (as a child device) - temperature sensor only works with some Qubino devices. 

@greens @dkirker @tpmanley @KKlimczukS @PKacprowiczS @ZWozniakS @MWierzbinskaS @BJanuszS 
Could you review this?

2020-05-08 20:01 UTC, greens commented
I think this will be on hold until we decide the correct way to proceed with https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/30326 . I don't think the model being used is the correct way forward.

2020-06-12 11:10 UTC, MGoralczykS commented
@greens I removed some settings. I discussed them with @KKlimczukS 
Also, there is one setting that needs to be discussed. 
I mean setting #100 Enable / Disable Endpoint I2 or select Notification Type and Event 
(https://products.z-wavealliance.org/products/1336). Should I add this? This setting occurs in other relays too.
What do you think about this?

2020-06-12 19:08 UTC, greens commented
We're not going to be using parameter 100.

2020-06-12 19:09 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +			case "boolRange":
this device has no "boolRange" parameter and a lot of the boilerplate is dedicated to it.

Pare this list down to the actual types included in this PR and also inline most of this code

2020-06-12 19:09 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +}
this code is obsolete

2020-06-12 19:10 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +	sendEvent(name: "checkInterval", value: 2 * 15 * 60 + 2 * 60, displayed: false, data: [protocol: "zwave", hubHardwareId: device.hub.hardwareID, offlinePingable: "1"])
should not be offlinePingable

2020-06-12 19:10 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +	}
remove

2020-06-12 19:10 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +}
should not be a separate function

2020-06-12 19:11 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +            commands += encap(zwave.configurationV2.configurationSet(scaledConfigurationValue: getCommandValue(it), parameterNumber: it.parameterNumber, size: it.size))
nit: spacing

2020-06-12 19:13 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +		description: "Support output Switch selection Set value means the type of the device that is connected to the output. The device type can be normally open (NO) or normally close (NC).  "
"Set the type of device connected to the output"

2020-06-12 19:13 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +		description: "Defines the type of switch connected to Input 2 "
how is input 2 being handled?

2020-06-18 12:51 UTC, MGoralczykS commented
@greens I changed those things that you mentioned and I added events which are handling temperature.

2020-06-18 21:22 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +	commands << zwave.manufacturerSpecificV2.manufacturerSpecificGet().format()
remove this get

2020-06-18 21:22 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +	commands << zwave.associationV1.associationSet(groupingIdentifier:6, nodeId:[zwaveHubNodeId]).format()
can you comment what each association group is responsible for?

2020-06-18 21:26 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +		childDevice = childDevices.find { it.deviceNetworkId == childDni }
you return the child device from `createChildDevice` you don't need to search for it

2020-06-18 21:27 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +def createChildDevice(childDthNamespace, childDthName, childDni, childComponentLabel) {
you only ever call this one time with one set of arguments, you should probably just hard-code them inside the function

2020-06-18 21:30 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +			zwave.basicV1.basicGet().format()
(here and several other places) Why are you only occasionally using `encap`? You _should_ be using it everywhere.

2020-06-18 21:30 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +		def childDevice = childDevices.find { it.deviceNetworkId == childDni }
you could just do `childDevice?.find` instead of wrapping this in an if statement

2020-06-18 21:33 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +				)
just put each of these input blocks on one line

I'd rather they be very long than clutter the DTH vertically

2020-06-25 12:28 UTC, MGoralczykS commented
@greens I fiexd those things that you have mentioned. Could you check it?

2020-06-25 19:13 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +		childDevice = createChildDevice("qubino", "Child Temperature Sensor", childDni, "Qubino Temperature Sensor")
We had to rename this to "Qubino Temperature Sensor"

2020-06-29 13:55 UTC, MGoralczykS commented
I created a new file Qubino Flush Relay to have there two Qubino Relays 1D and 1. I added 3 settings only for new Relay. Also changed those things that you wanted. Could you check it?

2020-06-30 00:38 UTC, greens requested changes
You have to change the name of the DTH used to create the child device to "Qubino Temperature Sensor". "Child Temperature Sensor" does not exist in the "qubino" namespace.

2020-06-30 11:21 UTC, MGoralczykS commented
@greens Fixed

2020-06-30 18:06 UTC, greens commented on devicetypes/smartthings/qubino-flush-1d-relay.src/qubino-flush-1d-relay.groovy
> +		childDevice = createChildDevice("qubino", "Child Temperature Sensor", childDni, "Qubino Temperature Sensor")
I don't know how you're not seeing this comment.

2020-06-30 18:07 UTC, greens commented on devicetypes/smartthings/qubino-flush-relay.src/qubino-flush-relay.groovy
> +		childDevice = createChildDevice("smartthings", "Qubino Temperature Sensor", childDni, "Qubino Temperature Sensor")
This isn't the one I wanted you to change.

"Qubino Temperature Sensor" is in the "qubino" namespace.

"Child Temperature Sensor" is in the "smartthings" namespace.

You want to use "qubino" "Qubino Temperature Sensor"

2020-07-01 11:17 UTC, MGoralczykS commented
@greens Fixed

2020-07-01 22:48 UTC, greens commented
No. It's not. You haven't addressed _any_ of my comments on `qubino-flush-1d-relay.groovy`

2020-07-02 10:23 UTC, MGoralczykS commented
@greens In my local repo I deleted qubino-flush-1d-relay because those Relays will be in one DTH.

2020-07-02 19:29 UTC, greens commented
@MGoralczykS you needed to `git rm` it. It still shows up in this PR.

2020-07-06 10:33 UTC, MGoralczykS commented
@greens Done

2020-07-06 20:39 UTC, greens commented on devicetypes/smartthings/qubino-flush-relay.src/qubino-flush-relay.groovy
> +		capability "Temperature Measurement"
this device shouldn't support temperature measurement since that's entirely on the child device.

2020-07-06 20:42 UTC, greens commented on devicetypes/smartthings/qubino-flush-relay.src/qubino-flush-relay.groovy
> +		name: "Input 3 contact type", key: "input3ContactType", type: "boolean",
So, if we're not surfacing the switches attached to input 1 and 3 at all anyway, why are these preferences here? 

I thought we were just going to add them as simple switch (or contact sensor) child devices?

2020-07-06 20:42 UTC, greens commented
Can you remind me why this is a separate DTH (as you've implemented it) and not part of `flush-2-relay`

2020-07-09 06:50 UTC, MGoralczykS commented
@greens When I started working on this device we didn't have `flush-2-relay`. I will add these devices to `flush-2-relay`.

2020-07-14 14:11 UTC, MGoralczykS commented
@greens Could you check this PR -> https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/37124 ?

2020-07-14 18:03 UTC, greens commented
Yeah. You can close this one.

2020-07-15 06:23 UTC, closed without merging