ICP-4820 - Fix activity polling
SmartThingsCommunity/SmartThingsPublic pull request #3196
Opened 2018-06-26 17:14 UTC by juano2310

2018-06-26 21:53 UTC, marstorp commented on smartapps/smartthings/logitech-harmony-connect.src/logitech-harmony-connect.groovy
> +						def childDevice = getChildDevice(activity.deviceNetworkId)
if activities = getChildDevices(), isn't the activity in this each loop the child for which you getChidlDevice(activity.deviceNetworkId)? Do you really need to getChildDevice again here, can't you just use activity, granted the name is a but obscure...?

2018-06-26 22:00 UTC, marstorp commented on smartapps/smartthings/logitech-harmony-connect.src/logitech-harmony-connect.groovy
> +					if ("${activity.deviceNetworkId}".contains("harmony-${it.key}")) {
indentation.....

2018-06-26 22:05 UTC, marstorp commented on smartapps/smartthings/logitech-harmony-connect.src/logitech-harmony-connect.groovy
> +                def childDevice = getChildDevice(activity.deviceNetworkId)
Similare comment as above, isn't activities a list of childDevices? so you shouldn't have to do another getChildDevice() on a specific deviceNetworkId here...

2018-06-26 22:06 UTC, marstorp requested changes
Please answer the questions and/or update the code

2018-06-27 00:26 UTC, surfous requested changes
The changes themselves look alright, though I have the same questions about using the activity device at hand that Ingvar has asked, rather than re-querying by device ID. 

Indentation is very inconsistent throughout the file, and makes reading the code and identifying blocks very challenging. Please take the time to normalize the indentation throughout for the sake of maintainability. Whomever will work on this in the future (including yourself) will thank you!

2018-06-27 16:28 UTC, marstorp approved these changes
LGTM ⛵️

2018-06-27 18:03 UTC, surfous approved these changes
Thanks for the cleanup - it's much easier to follow the nested blocks of code at a glance.

2018-06-27 18:07 UTC, merged