[WWST-1150 ]DTH for 4 endpoint Ecolink Siren
SmartThingsCommunity/SmartThingsPublic pull request #3328
Opened 2018-08-03 15:52 UTC by MMateusiakS

@greens @MAblewiczS  @DCzarneckaS DTH ready for review

2018-08-06 18:16 UTC, greens commented on devicetypes/smartthings/ecolink-wireless-siren.src/ecolink-wireless-siren.groovy
> +	sendEvent(name: "switch", value: "on")
We shouldn't need to synthesize this event here. The `basicGet` should take care of that for us.

2018-08-06 18:16 UTC, greens commented on devicetypes/smartthings/ecolink-wireless-siren.src/ecolink-wireless-siren.groovy
> +	for (i in 2..4) {
you could use `endPoints.each` here

2018-08-06 18:17 UTC, greens commented on devicetypes/smartthings/ecolink-wireless-siren.src/ecolink-wireless-siren.groovy
> +def multiChannelCmdEncapCmd(cmd, endPoint) {
this and `encap` appear to be the same function

2018-08-06 18:20 UTC, greens commented on devicetypes/smartthings/ecolink-wireless-siren.src/ecolink-wireless-siren.groovy
> +def sendCommand(device, commands) {
why not just have the child devices send their endpoint number instead of parsing it out of the DNI?

2018-08-06 18:23 UTC, greens requested changes
I think you'll want to look at the zwave-siren DTH. It's important that we use the "Alarm" capability. It will essentially be redundant with "Switch", but it's important for how the device is presented and used. Speaking of which, using the generic-switch ui-metadata won't work, because that will cause the device to show up as a switch instead of an alarm/siren. Use the `generic-siren` metadata instead.

2018-08-07 15:02 UTC, MMateusiakS commented
Hey @greens , I have made changes according to your comments. Thanks for advice about Alarm capability! Waiting for second review.

2018-08-07 22:21 UTC, greens commented on devicetypes/smartthings/ecolink-wireless-siren.src/ecolink-wireless-siren.groovy
> +		val = "off"
you've already defined `val` as `"off"` here, so you can just check for `!= 0`

2018-08-07 22:23 UTC, greens commented on devicetypes/smartthings/ecolink-wireless-siren.src/ecolink-wireless-siren.groovy
> +		val = "off"
you could use another ternary operator here like you do for `value1`

2018-08-08 20:21 UTC, greens approved these changes

2018-08-08 20:21 UTC, merged