[WWST-1222] Initial commit for Ecolink Flood & Freeze Sensor.
SmartThingsCommunity/SmartThingsPublic pull request #3366
Opened 2018-08-16 13:58 UTC by PKacprowiczS

@greens @MAblewiczS @MMateusiakS @DCzarneckaS 
Please review.

2018-08-16 15:09 UTC, DCzarneckaS submitted a review, later dismissed

2018-08-16 21:48 UTC, greens requested changes
I'd copy the name we used for the Z-Wave version and call this "Ecolink Zigbee Water/Freeze Sensor". Other than that it looks fine.

2018-08-20 18:10 UTC, greens approved these changes

2018-08-20 18:11 UTC, greens approved these changes

2018-08-20 18:11 UTC, merged