DevWs for NIE-TECH CO., LTD. containing containing Z-Wave Switch Generic
SmartThingsCommunity/SmartThingsPublic pull request #33688
Opened 2020-06-10 03:21 UTC by sky-nie

2021-01-13 10:08 UTC, KKlimczukS commented
@sky-nie 
Since this branch has conflicts, could You resolve them first ?

2021-01-13 10:11 UTC, KKlimczukS requested changes

2021-01-13 10:11 UTC, KKlimczukS commented on devicetypes/smartthings/zwave-switch-generic.src/zwave-switch-generic.groovy
> +        fingerprint mfr: "0312", prod: "FF00", model: "FF0C", deviceJoinName: "Minoston Mini Plug", ocfDeviceType: "oic.d.smartplug" //Minoston Mini Smart Plug
(After resolving conflicts on this branch)
Please add a Raw Description in a comment after Your fingeprint (You can find it in the SmartThings graph api in device details) 
so the fingerprint would look like -> 

fingerprint mfr: "0312", prod: "FF00", model: "FF0C", deviceJoinName: "Minoston Mini Plug", ocfDeviceType: "oic.d.smartplug" //Minoston Mini Smart Plug, Raw Description (paste raw description here)

2021-03-04 15:57 UTC, k-morawski commented
Dear @sky-nie , @Winniewen18 , could you please check @KKlimczukS comments and reply? Please let us know if you need our help. Many thanks!

2021-03-05 09:07 UTC, sky-nie commented
> Dear @sky-nie , @Winniewen18 , could you please check @KKlimczukS comments and reply? Please let us know if you need our help. Many thanks!

Sorry to trouble you, I updated this document today。

2021-03-05 14:52 UTC, KKlimczukS commented
> > Dear @sky-nie , @Winniewen18 , could you please check @KKlimczukS comments and reply? Please let us know if you need our help. Many thanks!
> 
> Sorry to trouble you, I updated this document today。

@sky-nie , @Winniewen18
This branch still has conflicts. Please, could You resolve them first ?

2021-03-10 12:58 UTC, k-morawski commented
Dear @sky-nie , @Winniewen18, could you please resolve your branch conflicts and make small fix - add a Raw Description in a comment after Your device's fingeprint ? @KKlimczukS gave you more info on that in his comment from Jan 13. 
If you fix it, we will merge your PR. Many thanks

2021-03-11 03:18 UTC, closed without merging