[WWST-1445]   Updates DTH for Sengled E14-U43 Dimmer bulb
SmartThingsCommunity/SmartThingsPublic pull request #3389
Opened 2018-08-22 09:22 UTC by DCzarneckaS

@greens

2018-08-22 17:20 UTC, greens requested changes

2018-08-22 17:20 UTC, greens commented on devicetypes/smartthings/zll-dimmer-bulb.src/zll-dimmer-bulb.groovy
> +	definition(name: " 3ZLL Dimmer Bulb", namespace: "smartthings", vid: "generic-color-temperature-bulb", author: "SmartThings", ocfDeviceType: "oic.d.light", runLocally: true, minHubCoreVersion: '000.
Just make this a fingerprint change. 

Changing the name will break this DTH, and `zll dimmer bulb` already has custom metadata.

2018-08-22 17:25 UTC, tpmanley commented on devicetypes/smartthings/zll-dimmer-bulb.src/zll-dimmer-bulb.groovy
> +		//01 0104 0101 00 08 0000 0003 0004 0005 0006 0008 0702 0B05 01 0019
Please remove the comment and the extra newlines too

2018-08-22 17:26 UTC, tpmanley commented on devicetypes/smartthings/zll-dimmer-bulb.src/zll-dimmer-bulb.groovy
> + *	Copyright 2016 SmartThings
The indentation in the license should be left as is.

2018-08-22 17:27 UTC, tpmanley commented on devicetypes/smartthings/zll-dimmer-bulb.src/zll-dimmer-bulb.groovy
> +	definition(name: " 3ZLL Dimmer Bulb", namespace: "smartthings", vid: "generic-color-temperature-bulb", author: "SmartThings", ocfDeviceType: "oic.d.light", runLocally: true, minHubCoreVersion: '000.
Also `generic-color-temperature-bulb` would not be correct since this DTH doesn't support color temperature.

2018-08-27 15:32 UTC, tpmanley approved these changes

2018-08-27 18:35 UTC, greens approved these changes

2018-08-27 18:36 UTC, merged