ICP-5724 : Add OCF device type to Fibaro wall plugs
SmartThingsCommunity/SmartThingsPublic pull request #3400
Opened 2018-08-24 18:50 UTC by munds

cc @greens @workingmonk

2018-08-24 22:32 UTC, greens commented on devicetypes/fibargroup/fibaro-wall-plug-eu-zw5.src/fibaro-wall-plug-eu-zw5.groovy
> +	definition (name: "Fibaro Wall Plug EU ZW5", namespace: "FibarGroup", author: "Fibar Group", ocfDeviceType: "oic.d.martplug") {
typo. should be `smartplug`

2018-08-24 22:32 UTC, greens commented on devicetypes/fibargroup/fibaro-wall-plug-eu-zw5.src/fibaro-wall-plug-eu-zw5.groovy
> +	definition (name: "Fibaro Wall Plug EU ZW5", namespace: "FibarGroup", author: "Fibar Group", ocfDeviceType: "oic.d.martplug") {
in all of them actually

2018-08-24 22:32 UTC, greens requested changes
typo in all three

2018-08-27 23:15 UTC, munds commented
Made the requested changes, @greens

2018-08-28 17:30 UTC, greens approved these changes

2018-08-28 17:30 UTC, greens commented
going to merge this for you so it makes it to staging

2018-08-28 17:31 UTC, merged