Adding support for Aeotec Water sensor to generic DTH
SmartThingsCommunity/SmartThingsPublic pull request #3426
Opened 2018-08-30 21:00 UTC by aclly

2018-08-30 21:00 UTC, aclly commented
@greens Can you review this when you get a chance?

2018-08-30 21:25 UTC, greens commented on devicetypes/smartthings/zwave-water-sensor.src/zwave-water-sensor.groovy
> +        commands << zwave.configurationV1.configurationSet(parameterNumber: 0x5E, scaledConfigurationValue: 1, size: 1).format()
please describe what this parameter does in a comment

2018-08-30 21:25 UTC, greens requested changes
Can you revert back to tabs please?

2018-09-06 18:29 UTC, greens commented
@aclly ping

2018-09-06 18:43 UTC, aclly commented
We had a couple more things we needed to fix and are waiting on a firmware upgrade for the cell hub. Didn't want to push up the requested changes until it was ready to merge.

2018-09-17 15:26 UTC, closed without merging