[ICP-6497] Updates DTH parent and Child for Aeotec Dual Nano Switch
SmartThingsCommunity/SmartThingsPublic pull request #3579
Opened 2018-10-11 13:33 UTC by DCzarneckaS

@MAblewiczS  @greens

2018-10-11 16:51 UTC, tpmanley commented on devicetypes/smartthings/zwave-binary-switch-endpoint.src/zwave-binary-switch-endpoint.groovy
> +	response(refresh())
You need to return the combined results of both configure and refresh.

2018-10-12 07:52 UTC, MAblewicz requested changes

2018-10-12 07:52 UTC, MAblewiczS commented on devicetypes/smartthings/zwave-dual-switch.src/zwave-dual-switch.groovy
> +	response(refresh())
Move response(refresh) to configure() where You are already calling refresh or remove refresh there and combine like Tom said. First way looks easier

2018-10-15 09:00 UTC, DCzarneckaS commented
@MAblewiczS  Please check new commits.

2018-10-15 11:13 UTC, closed without merging