WWST-6822 Leviton Tamper Resistant Outlet ZW15R
SmartThingsCommunity/SmartThingsPublic pull request #35995
Opened 2020-07-02 13:37 UTC by BJanuszS

**WWST-6822**
A fingerprint for Leviton Tamper Resistant Outlet ZW15R has been added. 

@KKlimczukS @ZWozniakS @MWierzbinskaS @PKacprowiczS @MGoralczykS 

@greens @dkirker @tpmanley could you please take a look at it?

2020-07-02 20:06 UTC, greens commented on devicetypes/smartthings/zwave-switch-secure.src/zwave-switch-secure.groovy
> +		fingerprint mfr: "001D", prod: "0037", model: "0002", deviceJoinName: "Leviton Outlet" //Leviton Tamper Resistant Outlet ZW15R
If it's an outlet it should probably have a custom ocfDeviceType (`oic.d.smartplug`)

2020-07-02 20:06 UTC, greens requested changes
The `zwave-switch-secure` DTH is actually redundant now since encapsulation is handled by the hub. You should just be able to add this to `zwave-switch-generic`, but verify first.

2020-07-03 09:17 UTC, BJanuszS commented
@greens The device works with zwave-switch-generic. I've also added the 'oic.d.smartplug'. Please, take a look.

2020-07-06 20:16 UTC, greens commented on devicetypes/smartthings/zwave-switch-generic.src/zwave-switch-generic.groovy
> +        fingerprint mfr: "001D", prod: "0037", model: "0002", deviceJoinName: "Leviton Outlet", ocfDeviceType: "oic.d.smartplug" //Leviton Tamper Resistant Outlet ZW15R
nit: spacing

2020-07-07 08:36 UTC, BJanuszS commented on devicetypes/smartthings/zwave-switch-generic.src/zwave-switch-generic.groovy
> +        fingerprint mfr: "001D", prod: "0037", model: "0002", deviceJoinName: "Leviton Outlet", ocfDeviceType: "oic.d.smartplug" //Leviton Tamper Resistant Outlet ZW15R
@greens Ok, fixed now

2020-07-07 18:02 UTC, greens approved these changes

2020-07-07 18:02 UTC, merged