DevWs for CoolKit Technology Co.,Ltd containing containing ZigBee Multi Switch
SmartThingsCommunity/SmartThingsPublic pull request #36526
Opened 2020-07-08 02:33 UTC by jwg-123

2020-07-08 06:46 UTC, PKacprowiczS requested changes

2020-07-08 06:46 UTC, PKacprowiczS commented on devicetypes/smartthings/zigbee-multi-switch.src/zigbee-multi-switch.groovy
> +        fingerprint profileId: "0104", inClusters: "0000, 0003, 0005, 0004, 0006", manufacturer: "eWeLink", model: "ZB-SW02", deviceJoinName: "eWeLink Switch 1"
@jwg-123 please use tabs instead of spaces here

2020-07-08 06:46 UTC, PKacprowiczS commented on devicetypes/smartthings/zigbee-multi-switch.src/zigbee-multi-switch.groovy
> +    } else if (device.getDataValue("model") == "ZB-SW04") {
and also here in those _else if_ ... _else_ statements.

2020-07-17 14:29 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-multi-switch.src/zigbee-multi-switch.groovy
> +        fingerprint profileId: "0104", inClusters: "0000, 0003, 0005, 0004, 0006", manufacturer: "eWeLink", model: "ZB-SW02", deviceJoinName: "eWeLink Switch 1"
According to new fingerprint writing rules: 
- deviceJoinName should look like: deviceJoinName: "eWeLink Switch" (in Your every fingerprint)
- profileId, inClusters/outClusters are not needed anymore. You may remove it.
- please add Raw Descriptions in comments above each fingerprint
(You may find it in SmartThings GraphApi IDE / My Devices / (select device)  / (device details) -> Raw Description
so it should look like:
```
// Raw Description ...
fingerprint manufacturer: "eWeLink", model: "ZB-SW02", deviceJoinName: "eWeLink Switch"
```

2020-12-04 09:08 UTC, KKlimczukS commented
Proper changes were merged in 37787. I'm closing this PR.

2020-12-04 09:09 UTC, closed without merging