Icp 7154: change device name to chinese
SmartThingsCommunity/SmartThingsPublic pull request #3689
Opened 2018-11-19 10:35 UTC by FenMei007S

@tpmanley @varzac  Dear Tom and Zach, plz review it,and merage to china STG server. the device name should be changed to chinese

2018-11-19 15:18 UTC, tpmanley commented on devicetypes/smartthings/smartsense-motion-sensor.src/smartsense-motion-sensor.groovy
> +		fingerprint inClusters: "0000,0001,0003,0020,0402,0500", outClusters: "0019", manufacturer: "Samjin", model: "motion", deviceJoinName: "人体传感器"
These join names are used globally so we cannot change the join name to Chinese for the SmartSense Motion Sensor or SmartSense Multi Sensor.

2018-11-19 15:19 UTC, tpmanley requested changes
I'm not opposed to changing the join names for the devices sold in the Chinese market but the names for the devices sold globally should not be changed.

2018-11-20 02:48 UTC, FenMei007S commented
@ tpmanley, Is it possible only push the change to china server?

2018-12-10 08:22 UTC, scarlettw0913 commented
@tpmanley, we have verified chinese device names, only SDS doorlock device name still can not work, please help to check it, thanks~

2018-12-10 16:45 UTC, tpmanley commented
@scarlettw0913 , I verified the changes had been deployed already so I'll need some more information about the problem. Please hit me up in Slack

2018-12-12 09:11 UTC, FenMei007S commented
@tpmanley, Dear Tom, the switch's name change, it makes siwtch name incorrect, so update code to fix it.plz help to merage it to china server

2018-12-12 09:18 UTC, FenMei007S commented
change separator for new device name

2019-07-24 01:59 UTC, closed without merging