DevWs for frient containing containing Ozom Smart Siren
SmartThingsCommunity/SmartThingsPublic pull request #52672
Opened 2020-12-14 13:30 UTC by frient-design

2020-12-16 15:50 UTC, rboy1 commented
@KKlimczukS Konrad is this good?

2020-12-16 15:52 UTC, KKlimczukS requested changes

2020-12-16 15:52 UTC, KKlimczukS commented on devicetypes/smartthings/ozom-smart-siren.src/ozom-smart-siren.groovy
> +		fingerprint profileId: "0104", deviceId: "0403", inClusters: "0000,0003,0502,0500,0001", outClusters: "000A,0019", manufacturer: "frient A/S", model :"SIRZB-110", deviceJoinName: "frient Siren", mn
- profileId, deviceId, inClusters, outClusters are not necessary now, please remove them.
- please add the Raw Description (it may be found at graph.api.smartthings.com-> my devices ->  ) in a comment after Your fingerprint ->  // frient Smart Siren, Raw Description ...

2020-12-16 15:52 UTC, KKlimczukS commented on devicetypes/smartthings/ozom-smart-siren.src/ozom-smart-siren.groovy
> +	} else {
Please, could You refactor those if / else if statements so they would be more concise? 
else { if (...) -> else if (...)

2020-12-16 15:52 UTC, KKlimczukS commented on devicetypes/smartthings/ozom-smart-siren.src/ozom-smart-siren.groovy
> +private Boolean isFrientSensor() {
Shouldn't the name of this method be isFrientSiren() ?

2020-12-16 16:20 UTC, rboy1 commented on devicetypes/smartthings/ozom-smart-siren.src/ozom-smart-siren.groovy
> +	} else {
Konrad, this device only supports a single mode of operation hence it was carved out but I'll refactor it to make it more generic so it's expandable in future to additional devices with minimal code changes.

2020-12-16 17:41 UTC, rboy1 commented on devicetypes/smartthings/ozom-smart-siren.src/ozom-smart-siren.groovy
> +		fingerprint profileId: "0104", deviceId: "0403", inClusters: "0000,0003,0502,0500,0001", outClusters: "000A,0019", manufacturer: "frient A/S", model :"SIRZB-110", deviceJoinName: "frient Siren", mn
Done

2020-12-16 17:41 UTC, rboy1 commented on devicetypes/smartthings/ozom-smart-siren.src/ozom-smart-siren.groovy
> +private Boolean isFrientSensor() {
Done

2020-12-17 08:26 UTC, KKlimczukS approved these changes

2020-12-17 08:26 UTC, merged