DevWs for mixtile containing containing ZigBee Switch
SmartThingsCommunity/SmartThingsPublic pull request #55424
Opened 2021-01-11 06:29 UTC by dapbtxl

2021-01-13 14:01 UTC, MWierzbinskaS requested changes

2021-01-13 14:01 UTC, MWierzbinskaS commented on devicetypes/smartthings/zigbee-switch.src/zigbee-switch.groovy
> -		fingerprint manufacturer: "Jasco Products", model: "43076", deviceJoinName: "Enbrighten Switch" //Enbrighten, In-Wall Smart Switch 43076, Raw Description: 01 0104 0100 00 06 0000 0003 0004 0005 000
Please do not remove fingerprints of other partners

2021-01-13 14:01 UTC, MWierzbinskaS commented on devicetypes/smartthings/zigbee-switch.src/zigbee-switch.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0B05", outClusters: "0019", manufacturer: "Leviton", model: "DG15S", deviceJoinName: "Leviton Switch" //Leviton Lumina RF S
Please do not remove fingerprints of other partners

2021-01-13 14:01 UTC, MWierzbinskaS commented on devicetypes/smartthings/zigbee-switch.src/zigbee-switch.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0006", outClusters: "0006, 0019", manufacturer: "Third Reality, Inc", model: "3RSS009Z", deviceJoinName: "RealitySwitch Switch" //RealitySwitch-Gen
Please do not remove fingerprints of other partners

2021-01-13 14:01 UTC, MWierzbinskaS commented on devicetypes/smartthings/zigbee-switch.src/zigbee-switch.groovy
> +        fingerprint profileId: "0104", inClusters: "0000, 0004, 0005, 0006", outClusters: "0006, 0019", manufacturer: "Mixtile", model: "W10-WW80SR01", deviceJoinName: "Mixtile Relay Switch" // Mixti
Please add the following changes:
- change deviceJoinName to "Mixtile Switch"
- fix spacing - use 1 tab instead of 4 spaces

2021-01-29 15:54 UTC, MWierzbinskaS commented
I see that there was a new commit, but it is an empty commit which doesn't contain any changes. Please resolve conflicts and add changes.

2021-01-29 15:55 UTC, MWierzbinskaS requested changes
I see that there was a new commit, but it is an empty commit which doesn't contain any changes. Please resolve conflicts and add changes.

2021-02-24 08:10 UTC, KKlimczukS commented
@dapbtxl Any updates here ?

2021-03-05 13:28 UTC, k-morawski commented
Dear @dapbtxl and @MadiTang, could you please check @MWierzbinskaS review feedback? In case of any questions, please let us know. Many thanks!

2021-03-11 16:50 UTC, KKlimczukS commented
@dapbtxl @MadiTang 
It seems that Your last commit is not valid. Github notifies -> "This commit does not belong to any branch on this repository."
Please update Your code so we could continue the code review.

2021-03-22 15:34 UTC, MWierzbinskaS requested changes
@MadiTang Please resolve conflicts and add changes according to previous comments.

2021-03-23 02:15 UTC, Focalcrest-nordic requested changes
Change name

2021-03-23 02:19 UTC, closed without merging

2021-03-23 16:33 UTC, k-morawski commented
new PR is here: https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/61176