DevWs for frient containing containing Zigbee Non-Holdable Button
SmartThingsCommunity/SmartThingsPublic pull request #56135
Opened 2021-01-18 12:15 UTC by frient-design

2021-01-19 14:04 UTC, MWierzbinskaS requested changes

2021-01-19 14:04 UTC, MWierzbinskaS commented on devicetypes/smartthings/zigbee-non-holdable-button.src/zigbee-non-holdable-button.groovy
> +           //(isFrientButton() ? zigbee.onOffConfig() : [])
Please remove unnecessary comment

2021-01-19 14:04 UTC, MWierzbinskaS commented on devicetypes/smartthings/zigbee-non-holdable-button.src/zigbee-non-holdable-button.groovy
>      }
Please replace else if with an or. Returned values for both branches are the same.

2021-01-19 14:04 UTC, MWierzbinskaS commented on devicetypes/smartthings/zigbee-non-holdable-button.src/zigbee-non-holdable-button.groovy
> +           (isFrientButton() ? zigbee.configureReporting(0x000f, 0x0055, DataType.BOOLEAN, 0, 600, null) : [])
Please instead of 0x000f and 0x0055 use BINARY_INPUT_CLUSTER and ATTRIBUTE_PRESENT_VALUE to avoid magic numbers.

2021-01-19 15:48 UTC, rboy1 commented on devicetypes/smartthings/zigbee-non-holdable-button.src/zigbee-non-holdable-button.groovy
> +           (isFrientButton() ? zigbee.configureReporting(0x000f, 0x0055, DataType.BOOLEAN, 0, 600, null) : [])
Missed that, thanks. It's been fixed

2021-01-20 14:29 UTC, KKlimczukS approved these changes

2021-01-20 14:29 UTC, merged