WWST-5862, added FP for the SAMSUMG LED
SmartThingsCommunity/SmartThingsPublic pull request #58370
Opened 2021-02-17 01:09 UTC by RaihaPark

Add a fingerprint for SAMSUNG LED in line 42 by LED marketing department request. They need it for marketing promotion.

2021-03-11 08:27 UTC, KKlimczukS commented
@RaihaPark This branch has conflicts that must be resolved first. Please, could You add Your changes on a fresh branch ?

2021-03-11 08:27 UTC, KKlimczukS requested changes
@RaihaPark This branch has conflicts that must be resolved first. Please, could You add Your changes on a fresh or rebased branch ?

2021-03-15 01:57 UTC, RaihaPark commented
@KKlimczukS Because of security policy, I can't rebase previous fork. So I deleted old one and make new fork and new pull request. Please see followed link.

https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/60609

2021-03-15 12:35 UTC, KKlimczukS commented
> @KKlimczukS Because of security policy, I can't rebase previous fork. So I deleted old one and make new fork and new pull request. Please see followed link.
> 
> #60609

@RaihaPark ok, so this pull request can be closed now.

2021-09-23 10:23 UTC, closed without merging