DevWs for TechniSat Digital GmbH containing containing TechniSat Single-Switch
SmartThingsCommunity/SmartThingsPublic pull request #61573
Opened 2021-03-25 13:50 UTC by SmartThings

2021-03-25 16:09 UTC, MWierzbinskaS requested changes
This DTH looks very similar to zwave-metering-switch DTH. I suggest moving this device fingerprint to zwave-metering-switch.
Is exposition of configuration parameters necessary for device to work properly? 
I think that some of them (e. g. Wattage meter report interval and Energy meter report interval) can be set to some default value in configure() method. 
E.g. like in this integration: https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/18317cd5cd8fb2b7255f96d132e26e11bd92bc26/devicetypes/smartthings/zwave-metering-switch.src/zwave-metering-switch.groovy#L256

2021-04-06 14:36 UTC, k-morawski commented
Dear @NArlt, could you please check @MWierzbinskaS's comment and reply/fix issues in your pull request? Many thanks

2021-04-07 08:03 UTC, NArlt commented
Hello @MWierzbinskaS,
Thanks for your quick review.
We noticed that our device is quite similar to the zwave-metering-switch, but we decided to create your own DTH because of the configuration. Some of the parameters depend on the hardware installation of the device and therefor it is not very wise to use default parameters. We also think it would be a bad idea to include our configuration handling into the generic zwave-metering-switch DTH.
For more information about our device you can contact me.
 
BR NArlt

2021-04-13 09:00 UTC, NArlt commented
Hi @k-morawski, @MWierzbinskaS,

Is there any decision how this pull-request should be handled? As described before we would like to keep our own DTH because we think the configuration is necessary to operate the device properly (depending on hardware installation). TechniSat plans to add 3 more devices with similar configurations and it would be nice to know if it is possible to add the own configuration or if  the 'generic' DTH has to be used.

BR NArlt

2021-04-13 09:51 UTC, MWierzbinskaS commented
@greens Could You please share your opinion about what do you think about integrating this device in a new DTH?

2021-04-13 12:46 UTC, MWierzbinskaS requested changes

2021-04-13 12:46 UTC, MWierzbinskaS commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> +	fingerprint mfr: "0299", prod: "0002", model: "1A90", deviceJoinName: "TechniSat On/Off switch"
Please add the following changes:

- change deviceJoinName to "TechniSat Switch"
- fix spacing - use 1 tab instead of 4 spaces
- delete unnecessary comments from file

2021-04-13 12:46 UTC, MWierzbinskaS commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> +	capability "Health Check"
Capabilities: actuator, light and sensor are deprecated. Please remove them.

2021-04-14 08:21 UTC, NArlt commented
Hi @k-morawski, @MWierzbinskaS,
how can I commit the requested changes to this pull request?
We created the publish request with the Developer Workspace without GutHub integration (not available in Europe). So the commit is not taken from my fork. I also have not the permission to change the file in the branch of this pull request. Do we have to create a new publish request with the changes in Developer Workspace or is there a way to commit the changes to this pull request.

Thanks in advanced.

BR NArlt

2021-04-14 15:01 UTC, MWierzbinskaS commented
@NArlt You can create a new PR from your fork on Github and link it in this PR.

2021-04-15 06:33 UTC, NArlt commented
created new PR #63424

2021-08-26 12:31 UTC, k-morawski commented
I am closing this pull request.

2021-08-26 12:31 UTC, closed without merging