DevWs for www.easyiot.tech containing containing ZigBee Switch
SmartThingsCommunity/SmartThingsPublic pull request #61971
Opened 2021-03-31 01:33 UTC by jwg-123

2021-03-31 08:44 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-switch.src/zigbee-switch.groovy
> +        fingerprint profileId: "0104", inClusters: "0000,0003,0004,00005,0006", outClusters: "0000", manufacturer: "LELLKI", model: "JZ-ZB-001", deviceJoinName: "LELLKI Switch"
Please fix indentation here (change 4 spaces to 1 tab) and add a Raw description in a comment after Your fingerprint.

2021-03-31 08:48 UTC, KKlimczukS requested changes

2021-03-31 08:48 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-switch.src/zigbee-switch.groovy
> +        fingerprint profileId: "0104", inClusters: "0000,0003,0004,00005,0006", outClusters: "0000", manufacturer: "LELLKI", model: "JZ-ZB-001", deviceJoinName: "LELLKI Switch"
Please fix indentation here (change 4 spaces to 1 tab).

2021-03-31 08:48 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-switch.src/zigbee-switch.groovy
> -		fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0019", outClusters: "0019", manufacturer: "Focalcrest", model: "SRB01", deviceJoinName: "Focalcrest Switch" // In-Wall Rela
Please add Your changes on a new branch (or rebase existing one)

2021-04-01 14:26 UTC, k-morawski commented
Dear @jwg-123 , could you please close this pull request? I believe it is obsolete now as you requested a newer pull request here: https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/62113 
Many thanks!

2021-04-07 06:44 UTC, KKlimczukS commented
Since #62113 was approved and  merged, I'm closing this PR

2021-04-07 06:45 UTC, closed without merging