DevWs for Sinope Technologies containing containing VA4200WZ-VA4200ZB Sinope Valve
SmartThingsCommunity/SmartThingsPublic pull request #63419
Opened 2021-04-14 20:14 UTC by SmartThings

2021-04-19 13:09 UTC, KKlimczukS requested changes

2021-04-19 13:09 UTC, KKlimczukS commented on devicetypes/sinope-technologies/va4200wz-va4200zb-sinope-valve.src/va4200wz-va4200zb-sinope-valve.groovy
> +    def LevelValue;
Please start the variable name from a lower case.

2021-04-19 13:09 UTC, KKlimczukS commented on devicetypes/sinope-technologies/va4200wz-va4200zb-sinope-valve.src/va4200wz-va4200zb-sinope-valve.groovy
> +    // def LevelsTable = [0, 20000, 40000, 60000, 80000, 100000];
Is this block of commented lines necessary here ?

2021-04-19 13:09 UTC, KKlimczukS commented on devicetypes/sinope-technologies/va4200wz-va4200zb-sinope-valve.src/va4200wz-va4200zb-sinope-valve.groovy
> +    def LevelsTable = [0, 20000, 40000, 60000, 80000, 100000];
Please start the variable name from a lower case.

2021-04-19 13:09 UTC, KKlimczukS commented on devicetypes/sinope-technologies/va4200wz-va4200zb-sinope-valve.src/va4200wz-va4200zb-sinope-valve.groovy
> +    def AnglesTable = [30, 55, 56, 57, 58.5, 60];
Please start the variable name from a lower case.

2021-04-19 13:09 UTC, KKlimczukS commented on devicetypes/sinope-technologies/va4200wz-va4200zb-sinope-valve.src/va4200wz-va4200zb-sinope-valve.groovy
> +    def RatioBetweenPointXandY = (LevelsTable[index] - LevelsTable[index - 1]) / (AnglesTable[index] - AnglesTable[index - 1]);
Please start the variable name from a lower case.

2021-04-19 13:09 UTC, KKlimczukS commented on devicetypes/sinope-technologies/va4200wz-va4200zb-sinope-valve.src/va4200wz-va4200zb-sinope-valve.groovy
> +    def AngleToAdd = LevelsTable[index] - (AnglesTable[index] * RatioBetweenPointXandY);
Please start the variable name from a lower case.

2021-04-19 13:09 UTC, KKlimczukS commented on devicetypes/sinope-technologies/va4200wz-va4200zb-sinope-valve.src/va4200wz-va4200zb-sinope-valve.groovy
> +    def LevelWithFactor = (RatioBetweenPointXandY * value) + AngleToAdd;
Please start the variable name from a lower case.

2021-04-19 13:09 UTC, KKlimczukS commented on devicetypes/sinope-technologies/va4200wz-va4200zb-sinope-valve.src/va4200wz-va4200zb-sinope-valve.groovy
> +    cmds += zigbee.readAttribute(0x0001, 0x0020)//refresh battery percentage remaining
Shouldn't You also change the text in this comment ? (percentage -> voltage)

2021-04-19 13:09 UTC, KKlimczukS commented on devicetypes/sinope-technologies/va4200wz-va4200zb-sinope-valve.src/va4200wz-va4200zb-sinope-valve.groovy
> +    cmds += zigbee.configureReporting(0x0001, 0x0020, 0x20, 60, 60*60, 1)//configure reporting battery percentage remaining min: 6sec, max 1hour
Shouldn't You also change the text in this comment ? (percentage -> voltage)

2021-04-26 13:33 UTC, k-morawski commented
Dear @vbeauregard-Sinope, could you please check and implement @KKlimczukS review feedback? Many thanks!

2021-05-06 14:37 UTC, vbeauregard-Sinope commented
@KKlimczukS @k-morawski  
This request can be rejected, we have created a new pull request with the Smartthings Workspace #65711 with the change suggested by KKlimczukS

2021-05-10 09:57 UTC, KKlimczukS commented
> @KKlimczukS @k-morawski
> This request can be rejected, we have created a new pull request with the Smartthings Workspace #65711 with the change suggested by KKlimczukS

@vbeauregard-Sinope 
Thank You. This pull request can be closed now.

2021-06-01 06:42 UTC, KKlimczukS commented
According to the above comment, I'm closing this PR.

2021-06-01 06:42 UTC, closed without merging