DevWs for TechniSat Digital GmbH containing containing TechniSat Single-Switch fixes
SmartThingsCommunity/SmartThingsPublic pull request #63424
Opened 2021-04-15 06:31 UTC by NArlt

2021-04-15 14:38 UTC, MWierzbinskaS requested changes

2021-04-15 14:38 UTC, MWierzbinskaS commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> + *	Copyright 2015 SmartThings
nit: its an old date

2021-04-15 14:38 UTC, MWierzbinskaS commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> +	definition (name: "TechniSat On/Off switch", namespace: "TechniSat", author: "TechniSat", vid:"generic-switch-power-energy",
Please add mnmn: "SmartThings" 
eg: https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/a7c980340992ca37508d42a70f354b5fd7d30048/devicetypes/smartthings/smartsense-motion-sensor.src/smartsense-motion-sensor.groovy#L20

2021-04-15 14:38 UTC, MWierzbinskaS commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> +				executeCommandsLocally: false, genericHandler: "Z-Wave")
genericHandler: "Z-Wave" can be removed

2021-04-15 14:38 UTC, MWierzbinskaS commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> +	}
This code is not necessary and can be removed

2021-04-16 07:06 UTC, NArlt commented
Implemented the requested changes

2021-04-19 14:42 UTC, MWierzbinskaS requested changes

2021-04-19 14:42 UTC, MWierzbinskaS commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> +		command "reset"
Could you please remove this custom command line. Custom commands are not supported anymore.

2021-04-19 14:42 UTC, MWierzbinskaS commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> +}
Could you please remove this function? It was used by custom commands which are not supported anymore.

2021-04-19 14:42 UTC, MWierzbinskaS commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> +def installed()
Could you please refactor formatting so it would look like:
def installed() {
...
}
Same applies to ifs, etc.

2021-04-20 07:16 UTC, NArlt commented
Implemented the requested changes

2021-04-20 19:49 UTC, greens commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> +	}
getting the mfr info is no longer necessary. you can remove this as well as the manufacturer specific report handler

2021-04-20 19:52 UTC, greens commented on devicetypes/technisat/technisat-on-off-switch.src/technisat-on-off-switch.groovy
> +				break
you don't have any "bool" preferences so this can be removed

2021-04-21 06:38 UTC, NArlt commented
Implemented the requested changes

2021-04-22 09:28 UTC, MWierzbinskaS approved these changes

2021-04-22 21:33 UTC, greens approved these changes

2021-04-22 21:33 UTC, merged