DevWs for TechniSat Digital GmbH containing containing TechniSat Shutter
SmartThingsCommunity/SmartThingsPublic pull request #66240
Opened 2021-05-12 12:32 UTC by SmartThings

2021-05-14 08:47 UTC, PKacprowiczS requested changes
Please use consistent indentation (preferably tabs). Also remember to follow style guidelines from https://github.com/greens/DTH_development (like spaces after `if`).
Some parts of code give me impression that you haven't verified at all if device works correctly with this DTH. Please provide requested changes and actually test device with SmartThings ecosystem.

2021-05-14 08:47 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +				executeCommandsLocally: false) {
remove `runLocally`, `minHubCoreVersion` and `executeCommandsLocally` flags

2021-05-14 08:47 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +}
Is this required by the device? If not, please remove this method.

2021-05-14 08:47 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +}
Is this required by the device? If not, please remove this method.

2021-05-14 08:47 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +				executeCommandsLocally: false) {
This `vid` doesn't support Power Meter and Energy Meter.
You can create your own presentation using SmartThings CLI.
Please see https://smartthings.developer.samsung.com/docs/devices/device-profile.html#Device-Presentation and https://github.com/SmartThingsCommunity/smartthings-cli#smartthings-capabilitiespresentation-id-version

2021-05-14 08:47 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +        capability "Switch Level"   // until we get a Window Shade Level capability
use `"Window Shade Level"` capability instead

2021-05-14 08:47 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +		fingerprint mfr: "0299", prod: "0005", model: "1A93", deviceJoinName: "TechniSat Shutter"
Change `deviceJoinName` to `TechniSat Window Treatment`

2021-05-27 10:44 UTC, NArlt commented
Hi @PKacprowiczS ,
sorry for the late reply. 
According to the VID of the DTH: I know the currently available VIDs do not support energy and power metering. TechniSat tested the DTH and is fine without the metering in the view for now, but they will maybe decide to add it later. So I implemented the support already. If this is a Problem I will remove the capabilities. I will fix the other requested changes in a new PR and link it here.

BR NArlt

2021-05-31 14:07 UTC, NArlt commented
Created new PR #67400

2021-06-01 09:02 UTC, k-morawski commented
> #67400

Thank you @NArlt , we will review your new PR: https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/67400. Could you please close https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/66240?

Many thanks!

2021-06-02 07:01 UTC, NArlt commented
Hi @k-morawski ,
just to play it safe: This PR is created with DevWs. So I have no permission to simply close this PR. To close it, I have to cancel the publish request in DevWs. Canceling the request will not abort the publish process?

BR NArlt

2021-06-02 11:33 UTC, k-morawski commented
> Hi @k-morawski ,
> just to play it safe: This PR is created with DevWs. So I have no permission to simply close this PR. To close it, I have to cancel the publish request in DevWs. Canceling the request will not abort the publish process?
> 
> BR NArlt

Thank you for explanation @NArlt . I wasn't aware about it. Please leave PR https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/66240 open. Thank you!

2021-08-26 12:32 UTC, k-morawski commented
I am closing this pull request.

2021-08-26 12:32 UTC, closed without merging