Devws for shina system containin 66
SmartThingsCommunity/SmartThingsPublic pull request #66551
Opened 2021-05-17 04:33 UTC by shinasys

2021-05-17 04:44 UTC, shinasys commented
@greens https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/63302#issuecomment-840832581 

> I imagine that difficulty you were having was because you had runLocally and executeCommandsLocally set to true.

So I deleted the runLocally and executeCommandLocally parameters and I added contact sensor again. 
Please checking.

2021-05-20 01:09 UTC, greens commented
@shinasys did that solve your problem? I don't have your device.

2021-05-20 01:58 UTC, shinasys commented
@greens Yes. I tested it.

2021-05-24 14:13 UTC, PKacprowiczS requested changes
Overall, looks good. I'd squash those commits if I were you.

2021-05-24 14:13 UTC, PKacprowiczS commented on devicetypes/shinasys/sihas-multipurpose-sensor.src/sihas-multipurpose-sensor.groovy
> +    if(isDSM300()) {
nit: spaces after `if`.

2021-05-24 14:13 UTC, PKacprowiczS commented on devicetypes/shinasys/sihas-multipurpose-sensor.src/sihas-multipurpose-sensor.groovy
> +    	refreshCmds +=  zigbee.enrollResponse()
nit: one space too many after `+=`

2021-05-27 21:52 UTC, greens approved these changes

2021-05-27 21:52 UTC, merged