DevWs for www.easyiot.tech containing containing Zigbee Non-Holdable Button
SmartThingsCommunity/SmartThingsPublic pull request #66778
Opened 2021-05-20 02:16 UTC by jwg-123

2021-05-20 08:22 UTC, PKacprowiczS requested changes

2021-05-20 08:22 UTC, PKacprowiczS commented on devicetypes/smartthings/zigbee-non-holdable-button.src/zigbee-non-holdable-button.groovy
> +        fingerprint manufacturer: "eWeLink", model: "KF01", deviceJoinName: "Smart Button" // 01 0104 0402 00 04 0000 0003 0500 0001 01 0003
Change `deviceJoinName` to `eWeLink Button`.

2021-05-20 09:07 UTC, k-morawski commented
Dear @jwg-123 , could you please close this PR? We can see your next request with a new PR: https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/66779. We will review it. Hope that's fine. Many thanks, Kamil

2021-08-26 12:11 UTC, k-morawski commented
I am closing this pull request. Connected integration request has been failed.

2021-08-26 12:11 UTC, closed without merging