DevWs for TechniSat Digital GmbH containing containing TechniSat Shutter fixes
SmartThingsCommunity/SmartThingsPublic pull request #67400
Opened 2021-05-31 14:07 UTC by NArlt

2021-06-01 09:07 UTC, PKacprowiczS requested changes
I'm sorry, but I'll insist on creating a new vid, which would include Power and Energy Meters. If you'll have any troubles creating it, don't hesitate to contact us.

2021-06-01 09:07 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +        capability "Switch Level"
don't use both `"Switch Level"` and `"Window Shade Level"` and the same time

2021-06-01 09:07 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +    sendEvent(name: "supportedWindowShadeCommands", value: JsonOutput.toJson(["open", "close", "pause"]), displayed: false)
Wrong indentation.

2021-06-01 09:07 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +    def levelEvent = createEvent(name: "level", value: level, unit: "%")
If you want to send an event to `Window Shade Level` capability, use `"shadeLevel"` as event's name

2021-06-01 09:07 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +}
This method is deprecated, it may be removed.

2021-06-02 07:30 UTC, NArlt commented
Hi @PKacprowiczS ,
I've read the documentation and downloaded the SmartThings CLI. Unfortunately I don't know how to start. The documentation mentioned it is possible to create device-profiles with the DevWs, but this is not possible for hub-connected devices. So it seems I have to  start from scratch with SmartThings CLI. Is there a an example, tutorial or a step-by-step manual how to create the necessary structs for creating a vid for our device? I only worked with hub-connexted devices in the DevWs and therefor I'm not very experienced outside the DTH.

Thanks in advance.

BR NArlt

2021-06-02 08:16 UTC, PKacprowiczS commented
@NArlt some insights about generating device presentation can be found here: https://community.smartthings.com/t/custom-capability-and-cli-developer-preview/197296 (start from `Generate / Post Device Configuration` section, since you don't use custom capabilities).

2021-06-03 11:41 UTC, NArlt commented
@PKacprowiczS ,
thanks for the link!
With this tutorial I was able to create our own vid. The new view is atm in review. I will commit the changes as soon as it is approved by TechniSat.

2021-06-09 13:06 UTC, NArlt commented
@PKacprowiczS ,
TechniSat approved the new view. But they decided to change the deviceJoinName back to 'TechniSat Roller Shutter Switch', which is the product name of this device. I hope this is acceptable for you.

2021-06-10 05:58 UTC, PKacprowiczS requested changes
Unfortunately, all deviceJoinNames must follow same scheme, so it can't be `Roller Shutter Switch`.

2021-06-10 05:58 UTC, PKacprowiczS commented on devicetypes/technisat/technisat-roller-shutter-switch.src/technisat-roller-shutter-switch.groovy
> +		fingerprint mfr: "0299", prod: "0005", model: "1A93", deviceJoinName: "TechniSat Roller Shutter Switch"
Please change name back.

2021-06-10 13:11 UTC, PKacprowiczS approved these changes
@greens @KKlimczukS

2021-06-11 22:18 UTC, greens approved these changes

2021-06-11 22:18 UTC, merged

2021-06-11 22:19 UTC, greens commented
This will be in production on the 22nd (California time)