DevWs for Smartenit, Inc containing containing EVSE
SmartThingsCommunity/SmartThingsPublic pull request #70221
Opened 2021-07-07 21:45 UTC by lecontr

2021-07-12 14:10 UTC, KKlimczukS requested changes

2021-07-12 14:10 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +		}
Could You put closing bracket and "else" statement in one line ?
```
} else {
...
}
```

2021-07-12 14:10 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> + @Field final MeteringCluster = 0x0702
You may use Zigbee.SIMPLE_METERING_CLUSTER constant instead of this one.

2021-07-12 14:10 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +			}
Could You put closing bracket and "else if" statement in one line ?
`} else if {`

2021-07-12 17:38 UTC, lecontr commented
Okay! Adjustments made and committed. 🙂 Thank you.

2021-07-13 13:40 UTC, KKlimczukS requested changes

2021-07-13 13:40 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +		} else { sendEvent(event) }
Does the whole block have to be in one line ?

2021-07-13 13:40 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +                	return sendEvent(name:"energy", value: getFPoint(mapDescription.value)/EnergyDivisor)
Nit: please correct spacing here

2021-07-13 13:40 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +			break;
Could You remove empty spaces after the `break;` ?

2021-07-13 13:40 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +    // updated() doesn't have it's return value processed as hub commands, so we have to send them explicitly
Nit: spacing (please change 4 spaces to 1 tab)

2021-07-13 14:15 UTC, KKlimczukS requested changes

2021-07-13 14:15 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +def configureHealthCheck() {
Can you only configure health check in this method and not return refresh() commands here ? (call refresh() method separately)

2021-07-14 07:20 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +					return sendEvent(name:"power", value: getFPoint(mapDescription.value/EnergyDivisor))
Could You confirm that EnergyDivisor should be used in both cases ? (power and energy events)

2021-07-14 07:20 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +def configureHealthCheck() {
Now it looks like refresh() is not called anywhere in this DTH.

2021-07-14 07:20 UTC, KKlimczukS commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +}
```suggestion
def configure() {
	log.debug "in configure()"
	configureHealthCheck()
	return (zigbee.configureReporting(zigbee.SIMPLE_METERING_CLUSTER, MeteringCurrentSummation, 0x25, 0, 600, 50) +
		zigbee.configureReporting(zigbee.SIMPLE_METERING_CLUSTER, MeteringInstantDemand, 0x2a, 0, 600, 50) +
		zigbee.configureReporting(EVSECluster, ChargingStatus, 0x30, 0x0, 0x0, null, [mfgCode: SmartenitMfrCode]) +
		refresh() 
	)
}
```

2021-07-14 20:21 UTC, lecontr commented on devicetypes/smartenit/smartelek-evse.src/smartelek-evse.groovy
> +					return sendEvent(name:"power", value: getFPoint(mapDescription.value/EnergyDivisor))
I've confirmed that energy divisor is used in both of these cases. 🙂

2021-07-15 19:37 UTC, greens approved these changes

2021-07-15 19:38 UTC, greens commented
@KKlimczukS just need your approval

2021-07-16 06:42 UTC, KKlimczukS approved these changes

2021-07-16 06:42 UTC, merged