DevWs for Smartenit, Inc containing containing ZBALRM
SmartThingsCommunity/SmartThingsPublic pull request #71537
Opened 2021-07-21 22:58 UTC by lecontr

2021-08-26 15:19 UTC, KKlimczukS requested changes

2021-08-26 15:19 UTC, KKlimczukS commented on devicetypes/smartenit/smartenit-zigbee-alarm.src/smartenit-zigbee-alarm.groovy
> +	definition (name: "Smartenit Zigbee Alarm", namespace: "Smartenit", author: "Luis Contreras") {
Instead of creating a new DTH, please add the fingerprint of Your device to this existing DTH
https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/ozom-smart-siren.src/ozom-smart-siren.groovy
(some tweaks in the code might be needed too)

2021-08-27 00:15 UTC, lecontr commented on devicetypes/smartenit/smartenit-zigbee-alarm.src/smartenit-zigbee-alarm.groovy
> +	definition (name: "Smartenit Zigbee Alarm", namespace: "Smartenit", author: "Luis Contreras") {
Oh ok. Should I retract this pull request and create a new one for that DTH?

2021-08-27 07:07 UTC, KKlimczukS commented on devicetypes/smartenit/smartenit-zigbee-alarm.src/smartenit-zigbee-alarm.groovy
> +	definition (name: "Smartenit Zigbee Alarm", namespace: "Smartenit", author: "Luis Contreras") {
You don't have to. Just delete this new file (smartenit-zigbee-alarm.groovy) and commit your next changes to this PR.

2021-09-01 10:45 UTC, KKlimczukS requested changes

2021-09-01 10:45 UTC, KKlimczukS commented on devicetypes/smartthings/ozom-smart-siren.src/ozom-smart-siren.groovy
> +		fingerprint model: "ZBALRM", manufacturer: "Compacta", deviceJoinName: "Smartenit Alarm", mnmn: "SmartThings" // Smartenit Alarm
Please add a raw description in a comment after the fingerprint.

2021-09-02 05:55 UTC, KKlimczukS approved these changes

2021-09-02 05:55 UTC, merged