DevWs for CoolKit Technology Co.,Ltd containing containing eWeLink Button
SmartThingsCommunity/SmartThingsPublic pull request #72533
Opened 2021-08-03 08:44 UTC by mingwei0827

2021-08-03 14:04 UTC, PKacprowiczS requested changes

2021-08-03 14:04 UTC, PKacprowiczS commented on devicetypes/smartthings/ikea-button.src/ikea-button.groovy
> +
Couldn't we just get away with `isEWeLink()` and removing model checks, as there's no any device specific configuration and only some exceptions for all manufacturer's devices?

2021-08-03 14:04 UTC, PKacprowiczS commented on devicetypes/smartthings/ikea-button.src/ikea-button.groovy
> +		}
Please use
```
if (condition) {
	// statement
} else if (anotherCondition) {
	// statement
} else {
	// default statement
}
```
style.

2021-08-26 06:57 UTC, mingwei0827 commented on devicetypes/smartthings/ikea-button.src/ikea-button.groovy
> +		}
Hi, I have modified the code. Please review, thank you.

2021-08-26 12:02 UTC, PKacprowiczS requested changes

2021-08-26 12:02 UTC, PKacprowiczS commented on devicetypes/smartthings/ikea-button.src/ikea-button.groovy
> +		}
Please correct `if / else` block styling to the same I've asked for.
Quoted code should look like this
```
	} else if (isEWeLink()) {
		if (descMap.clusterInt == zigbee.ONOFF_CLUSTER) {
			buttonNumber = 1
			if (descMap.commandInt == 0x00) {
				buttonState = "held"
			} else if (descMap.commandInt == 0x01) {
				buttonState = "double"
			} else {
				buttonState = "pushed"
			}
		}
```

2021-11-16 03:03 UTC, closed without merging