DevWs for NIE-TECH CO., LTD. containing containing Min Smart Plug
SmartThingsCommunity/SmartThingsPublic pull request #74687
Opened 2021-08-26 07:50 UTC by sky-nie

2021-08-26 07:55 UTC, sky-nie commented
I have merged the DTH related to [the PR](https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/74232).

2021-08-26 14:32 UTC, PKacprowiczS requested changes

2021-08-26 14:32 UTC, PKacprowiczS commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +        }
Any device based checks won't work in `preferences {...}` block, as it's called before any device is created. So, in this case, as `isNewModel()` have a `device == null` check, this statement will be always `true`.

2021-08-26 14:32 UTC, PKacprowiczS commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +    if(isNewModel()){
lacking spaces - `if(isNewModel()){` -> `if (isNewModel()) {`. There's a couple of similar mistakes across the whole file, I'd be thankful if you'd fix them without pointing out each of them.

2021-08-26 14:32 UTC, PKacprowiczS commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +                child?.sendEvent(checkIntervalEvt)
`checkIntervalEvt` seems to be not declared

2021-08-26 14:32 UTC, PKacprowiczS commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +            "sky-nie",
You should have here `"smartthings"` namespace, instead of `"sky-nie"`, cause I don't see any `Child Button` DTH submitted with `"sky-nie"` namespace.

2021-08-26 14:32 UTC, PKacprowiczS commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +            "${device.deviceNetworkId}-BUTTON",
General rule to defining children's DNI is `"${device.deviceNetworkId}:<number>"`, so I guess in your case it would be `"${device.deviceNetworkId}:2"`

2021-08-26 14:32 UTC, PKacprowiczS commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +private isNewModel() {
`New Model` is kinda relative definition. I'd suggest naming this method more like `isButtonAvailable()`.

2021-08-26 14:32 UTC, PKacprowiczS commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +}
Move this method down to original `getLedModeOptions()` and change its name to something less plain, maybe like `getAlternativeLedOptions()`.

2021-08-26 14:32 UTC, PKacprowiczS commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +        0x9F: 1		// Security S2
Those additional empty spaces at ends are not necessary.

2021-08-26 14:32 UTC, PKacprowiczS commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +                    componentLabel: "${device.displayName}-Button"
```
label: "plugButton",
componentLabel: "${device.displayName[0..-8]} Button"
```

2021-08-27 01:09 UTC, sky-nie commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +            "${device.deviceNetworkId}-BUTTON",
OK,I modified it.

2021-08-27 01:11 UTC, sky-nie commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +    if(isNewModel()){
OK! I modified it.

2021-08-27 01:12 UTC, sky-nie commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +                child?.sendEvent(checkIntervalEvt)
OK! I fixed it.

2021-08-27 01:13 UTC, sky-nie commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +            "sky-nie",
Yes, I checked the code, I have repaced "sky-nie" with "smartthings".

2021-08-27 01:15 UTC, sky-nie commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +private isNewModel() {
OK, I replaced "isNewModel" with "isButtonAvailable".

2021-08-27 01:21 UTC, sky-nie commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +}
OK! I modified it.

2021-08-27 01:22 UTC, sky-nie commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +                    componentLabel: "${device.displayName}-Button"
OK! I modified it.

2021-08-27 01:26 UTC, sky-nie commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +        0x9F: 1		// Security S2
OK!  I removed them.

2021-08-27 02:21 UTC, sky-nie commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +        }
I don't think there is a problem with always displaying (I have changed them to always display). The problem is that the num in some ConfigParams needs to be dynamically configured, and I have never thought of a good way to solve it-or, num is configured when the ConfigParams is loaded and used?

2021-08-27 02:26 UTC, sky-nie commented
I have to close this PR because I changed the common Pairing Instructions of the project related this PR. and I will restart a new PR to add all produncts related this DTH.

2021-08-27 03:11 UTC, closed without merging

2021-08-27 05:16 UTC, PKacprowiczS commented on devicetypes/sky-nie/min-smart-plug.src/min-smart-plug.groovy
> +        }
Unfortunately, you cannot make any part of preferences dynamically change.