DevWs for NIE-TECH CO., LTD. containing containing Aeotec Wallmote
SmartThingsCommunity/SmartThingsPublic pull request #76102
Opened 2021-10-08 03:42 UTC by sky-nie

2021-10-08 03:49 UTC, sky-nie commented
We have repeatedly tested and found that after modifying the fingerprint, Minoston Wallmote is more likely to succeed when pairing to this DTH.

2021-10-08 06:10 UTC, PKacprowiczS requested changes

2021-10-08 06:10 UTC, PKacprowiczS commented on devicetypes/smartthings/aeotec-wallmote.src/aeotec-wallmote.groovy
> +        fingerprint model: "D001", mfr: "0312", prod: "0924", deviceJoinName: "Minoston Remote Control", mnmn: "SmartThings", vid: "generic-4-button" //Minoston Wallmote
Generally all fingerprints follow this order:
`mfr: "...", prod: "...", model: "..."`
so please, adjust yours.

2021-10-08 07:42 UTC, sky-nie commented on devicetypes/smartthings/aeotec-wallmote.src/aeotec-wallmote.groovy
> +        fingerprint model: "D001", mfr: "0312", prod: "0924", deviceJoinName: "Minoston Remote Control", mnmn: "SmartThings", vid: "generic-4-button" //Minoston Wallmote
OK, I modified it.

2021-10-08 08:03 UTC, PKacprowiczS approved these changes

2021-10-08 09:15 UTC, k-morawski commented
Dear @sky-nie , please let me know if this request is a new integration request or this is an update in DevWS of your previous MR40Z integration which is already approved. It would be better to request an update to existing integration. Otherwise in the catalog there will be two entries for the same device.
What's more there is a typo in pairing instructions: "Press the first button 5 times, until the LED indicator blink bue." bue should be probably replaced with blue. Could you please check it? Many thanks

2021-10-13 01:20 UTC, sky-nie commented
This is an update in DevWS of my previous MR40Z integration which is already approved. Now the DTH is updated, but I can't find the place to start the update request in the Developer Workspace (for the released product, if the product has not been modified), so I have to modify the product information  to start the update request.

2021-10-13 09:26 UTC, PKacprowiczS commented
Closing this PR, as partner canceled DevWS request connected to it.

2021-10-13 09:26 UTC, closed without merging