DevWs for SHINA SYSTEM containing containing Zigbee Power Meter
SmartThingsCommunity/SmartThingsPublic pull request #76343
Opened 2021-10-28 03:44 UTC by shinasys

2021-10-29 12:37 UTC, KKlimczukS requested changes

2021-10-29 12:37 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-power-meter.src/zigbee-power-meter.groovy
> +        fingerprint inClusters: "0000,0001,0003,0020,0B04,0702", outClusters: "0003,0004,0019", manufacturer: "ShinaSystem", model: "PMM-300Z1", deviceJoinName: "SiHAS Energy Monitor" // SIHAS Power
You may remove `inClusters` and `outClusters` from the fingerprint and add whole Raw Description in a comment after this fingerprint.

2021-11-01 01:19 UTC, shinasys commented on devicetypes/smartthings/zigbee-power-meter.src/zigbee-power-meter.groovy
> +        fingerprint inClusters: "0000,0001,0003,0020,0B04,0702", outClusters: "0003,0004,0019", manufacturer: "ShinaSystem", model: "PMM-300Z1", deviceJoinName: "SiHAS Energy Monitor" // SIHAS Power
I have a question.
I want to know about the energy value in capability "Energy Meter".
I think this value is the total amount of the measured. 
However, when tested, it seems to be the sum of 10 minutes.

2021-11-02 08:54 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-power-meter.src/zigbee-power-meter.groovy
> +        fingerprint inClusters: "0000,0001,0003,0020,0B04,0702", outClusters: "0003,0004,0019", manufacturer: "ShinaSystem", model: "PMM-300Z1", deviceJoinName: "SiHAS Energy Monitor" // SIHAS Power
@shinasys 
"Energy Meter" capability is for handling [Wh] (or [kWh]) reports.
"Power Meter" capability is for handling [W] reports.

2021-11-02 09:09 UTC, KKlimczukS requested changes

2021-11-02 09:09 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-power-meter.src/zigbee-power-meter.groovy
> +private getPowerDivisor() {  (isFrientSensor() || isPMM300Z1()) ? 1 : 1000 }
Fix spacing here (one space is enough).

2021-11-03 00:26 UTC, shinasys commented on devicetypes/smartthings/zigbee-power-meter.src/zigbee-power-meter.groovy
> +        fingerprint inClusters: "0000,0001,0003,0020,0B04,0702", outClusters: "0003,0004,0019", manufacturer: "ShinaSystem", model: "PMM-300Z1", deviceJoinName: "SiHAS Energy Monitor" // SIHAS Power
> @shinasys "Energy Meter" capability is for handling [Wh] (or [kWh]) reports. "Power Meter" capability is for handling [W] reports.
I know the difference between Energy Meter and Power Meter.  
What I want to know is whether the value of the Energy Meter is the total cumulative value of this device.
Or I wonder what it is.

2021-11-10 09:52 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-power-meter.src/zigbee-power-meter.groovy
> +        fingerprint inClusters: "0000,0001,0003,0020,0B04,0702", outClusters: "0003,0004,0019", manufacturer: "ShinaSystem", model: "PMM-300Z1", deviceJoinName: "SiHAS Energy Monitor" // SIHAS Power
Usually it should be total energy measured, but You can check it yourself by switching on the device (with some load) for a certain amount of time and see what it reports.

2021-11-10 09:53 UTC, KKlimczukS approved these changes

2021-11-10 09:53 UTC, merged