DevWs for YookSmart containing containing ZigBee Window Shade Battery
SmartThingsCommunity/SmartThingsPublic pull request #76356
Opened 2021-11-01 05:53 UTC by JeremeLau

2021-11-02 12:19 UTC, KKlimczukS requested changes
There are too many changes because of removing window "Shade Level capability".

2021-11-02 12:19 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> -		capability "Window Shade Level"
Why did You remove this capability ?

2021-11-02 12:19 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> -		fingerprint inClusters: "0000,0001,0003,0004,0005,0102", outClusters: "0019", manufacturer: "Smartwings", model: "WM25/L-Z", deviceJoinName: "Smartwings Window Treatment"
Why did You remove this fingerprint ?

2021-11-02 12:19 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> -				attributeState "shadeLevel", action:"setShadeLevel"
Why did You change this tileAttribute ?

2021-11-02 12:19 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
>  	tiles(scale: 2) {
tiles are not supported in the new ST app, so there is no need to change anything here.

2021-11-02 12:19 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> -
Why did You remove this ?

2021-11-02 12:19 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> -
Why did You change that ?

2021-11-05 02:05 UTC, dkirker requested changes
Please only add the changes to the fingerprint and this code to the battery handler with proper indenting:
```
    	if (isYooksmartOrYookee()) {
        	batteryLevel = batteryLevel >> 1
        }
```
Please do not change any of the other code unless it is necessary.

2021-11-05 02:05 UTC, dkirker commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> +	def level = device.currentValue("level")
This should be using `shadeLevel`.

2021-11-05 02:05 UTC, dkirker commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> +    	if (isYooksmartOrYookee()) {
Please indent this if statement by two tabs (use the tab character, not spaces).

2021-11-05 02:06 UTC, dkirker commented
I deleted some inline code comments as most of the inline code should NOT be changed. The only thing that should be changed is the addition of the if statement to the battery handler and possibly the modification of ONLY the Yooksmart and Yookee fingerprints.

2021-11-05 07:42 UTC, KKlimczukS requested changes

2021-11-05 07:42 UTC, KKlimczukS commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> +		fingerprint manufacturer: "yooksmart", model: "D10110", deviceJoinName: "yooksmart Window Treatment"
Please, could You add the raw description in the comment after each fingerprint ?

2021-11-05 08:24 UTC, KKlimczukS submitted a review, later dismissed

2021-11-05 08:25 UTC, KKlimczukS commented
LGTM
@dkirker

2021-11-08 17:22 UTC, dkirker commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> -	if (lastLevel == "undefined" || currentLevel == lastLevel) { //Ignore invalid reports
@KKlimczukS @JeremeLau I don't think that we want to remove this.

2021-11-08 17:24 UTC, dkirker requested changes
Still a couple more things to address.

2021-11-08 17:24 UTC, dkirker commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> +		valueTile("shadeLevel", "device.level", width: 4, height: 1) {
While the tiles are not used any more, for the sake of cleanliness, let's please not add this and below to the PR.

2021-11-08 17:24 UTC, dkirker commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> +		controlTile("levelSliderControl", "device.level", "slider", width:2, height: 1, inactiveLabel: false) {
While the tiles are not used any more, for the sake of cleanliness, let's please not add this and above to the PR.

2021-11-08 17:24 UTC, dkirker commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> -	if (lastLevel == "undefined" || currentLevel == lastLevel) { //Ignore invalid reports
@KKlimczukS  @JeremeLau I don't think that we want to remove this.

2021-11-10 10:10 UTC, KKlimczukS approved these changes, later dismissed

2021-11-10 10:10 UTC, KKlimczukS commented
@dkirker

2021-11-23 07:20 UTC, dkirker requested changes
There is still line 152 that I don't think needs editing. If there is a reason why you want to remove it please explain why.

2021-11-23 07:20 UTC, dkirker commented on devicetypes/smartthings/zigbee-window-shade-battery.src/zigbee-window-shade-battery.groovy
> -	if (lastLevel == "undefined" || currentLevel == lastLevel) { //Ignore invalid reports
@JeremeLau Please add the `|| currentLevel == lastLevel` back in this line. If there is a reason that you are removing it, please explain here. Thanks

2021-11-29 03:12 UTC, JeremeLau commented
> There is still line 152 that I don't think needs editing. If there is a reason why you want to remove it please explain why.

I have explained many times in other issues, cause it will block the UI rendering while someone try to re-open the blind when it is already in 100% with network error.

2021-12-22 02:09 UTC, JeremeLau commented
> There is still line 152 that I don't think needs editing. If there is a reason why you want to remove it please explain why.

I have explained many times in other issues, cause it will block the UI rendering while someone try to re-open the blind when it is already in 100% with network error.

2022-02-16 09:38 UTC, KKlimczukS approved these changes
lgtm
@dkirker

2022-02-17 00:05 UTC, dkirker approved these changes

2022-02-17 07:47 UTC, merged