DevWs for SHINA SYSTEM containing containing ZigBee Lock Without Codes
SmartThingsCommunity/SmartThingsPublic pull request #77212
Opened 2021-12-23 04:28 UTC by shinasys

2021-12-30 08:20 UTC, PKacprowiczS requested changes

2021-12-30 08:20 UTC, PKacprowiczS commented on devicetypes/smartthings/zigbee-lock-without-codes.src/zigbee-lock-without-codes.groovy
> +		if(isSiHASLock()) cmds += zigbee.configureReporting(CLUSTER_DOORLOCK, DOORLOCK_ATTR_DOORSTATE,DataType.ENUM8, 0, 3600, null)
nit: space after `if`

2021-12-30 08:20 UTC, PKacprowiczS commented on devicetypes/smartthings/zigbee-lock-without-codes.src/zigbee-lock-without-codes.groovy
> +	if(isSiHASLock()) cmds += zigbee.readAttribute(CLUSTER_DOORLOCK, DOORLOCK_ATTR_DOORSTATE)
nit: space after `if`

2021-12-30 09:40 UTC, PKacprowiczS commented
@greens @dkirker this request adds `Contact Sensor` capability to the DTH, but existing setups shouldn't be affected, as vids in use don't support it

2022-01-10 23:13 UTC, greens approved these changes

2022-01-10 23:14 UTC, greens commented
@PKacprowiczS lgtm, merge once you're happy with it

2022-01-11 03:20 UTC, dkirker approved these changes

2022-01-11 06:20 UTC, PKacprowiczS approved these changes

2022-01-11 06:21 UTC, merged