Update orvibo-Moisture-sensor.groovy
SmartThingsCommunity/SmartThingsPublic pull request #77886
Opened 2022-02-28 05:54 UTC by weihuan1111

update thirdreality battery percent report Update

2022-03-09 03:31 UTC, weihuan1111 commented
@greens please help to review the merge require,thanks

2022-03-09 23:16 UTC, greens requested changes
fix string comparison

2022-03-11 03:46 UTC, weihuan1111 commented
@greens hello, i have update the code and fix comparison, please help to review the merge require,thanks

2022-03-14 06:07 UTC, weihuan1111 reviewed
update orvibo-moisture-sensor.groovy

2022-03-14 17:34 UTC, greens commented on devicetypes/smartthings/orvibo-Moisture-Sensor.src/orvibo-Moisture-Sensor.groovy
> +	int application_thirdreality = application.toInteger()
don't use two variables for this, just cast immediately. `getDataValue().toInteger()`

2022-03-15 00:44 UTC, weihuan1111 reviewed
update

2022-03-15 00:45 UTC, weihuan1111 commented
@greens hello, i have update the code, please help to review the merge require,thanks

2022-03-15 14:42 UTC, greens approved these changes

2022-03-15 14:42 UTC, merged