DevWs for CoolKit Technology Co.,Ltd containing containing ZigBee Switch
SmartThingsCommunity/SmartThingsPublic pull request #77930
Opened 2022-03-10 05:53 UTC by mingwei0827

2022-03-11 09:04 UTC, dsobierajsk approved these changes

2022-03-11 09:10 UTC, dsobierajsk requested changes

2022-03-11 09:10 UTC, dsobierajsk commented on devicetypes/smartthings/zigbee-switch.src/zigbee-switch.groovy
> +		fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0020, FC57", outClusters: "0019", manufacturer: "SONOFF", model: "ZBMINI-L", deviceJoinName: "SONOFF ZBMINI-L" //SONOFF ZBM
Please change deviceJoinName to "SONOFF Plug"

2022-03-14 16:09 UTC, k-morawski commented on devicetypes/smartthings/zigbee-switch.src/zigbee-switch.groovy
> +		fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0020, FC57", outClusters: "0019", manufacturer: "SONOFF", model: "ZBMINI-L", deviceJoinName: "SONOFF ZBMINI-L" //SONOFF ZBM
Dear @mingwei0827 , could you please check Dawid's comment? Many thanks!

2022-03-17 08:33 UTC, dsobierajsk commented on devicetypes/smartthings/zigbee-switch.src/zigbee-switch.groovy
> +		fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0020, FC57", outClusters: "0019", manufacturer: "SONOFF", model: "ZBMINI-L", deviceJoinName: "SONOFF ZBMINI-L" //SONOFF ZBM
Dear @mingwei0827, if it is not a plug, please change deviceJoinName to "SONOFF Switch" according to naming convention seen in every fingerprint

2022-03-17 08:43 UTC, mingwei0827 commented
@dsobierajsk hi~I have corrected it. Please help to check whether it is OK, thank you~

2022-03-17 08:44 UTC, mingwei0827 commented
@dsobierajsk hi，I have corrected it. Please help to check whether it is OK, thank you。

2022-03-17 08:46 UTC, dsobierajsk approved these changes

2022-03-17 08:49 UTC, KKlimczukS approved these changes

2022-03-17 08:49 UTC, merged