update
SmartThingsCommunity/SmartThingsPublic pull request #78743
Opened 2022-07-19 03:05 UTC by weihuan1111

2022-07-19 09:09 UTC, weihuan1111 commented
@greens please help to review the merge require,thanks

2022-07-19 18:26 UTC, greens commented on devicetypes/smartthings/ikea-button.src/ikea-button.groovy
> +				}
this separate if statement is not required after the refactoring to move all the code into `getButtonEvent`

2022-07-19 18:27 UTC, greens commented on devicetypes/smartthings/ikea-button.src/ikea-button.groovy
> +	Map ThirdRealityButtonMapping = [
this looks unused

2022-07-19 18:27 UTC, greens requested changes
In addition to my other comments, you have mixed tabs and spaces in several places

2022-07-20 08:23 UTC, weihuan1111 commented
@greens please help to review the merge require,thanks

2022-07-20 21:10 UTC, greens commented on devicetypes/smartthings/ikea-button.src/ikea-button.groovy
> +		}
you still have mixed whitespace

2022-07-21 00:32 UTC, weihuan1111 commented
@greens I have update the code.

2022-07-21 21:05 UTC, greens approved these changes

2022-07-21 21:06 UTC, merged